"""Command-line entrypoint for the WD Hydrus Tagger utility.

This module provides a Click-based CLI that queries a Hydrus server for files
and applies tags generated by a local tagging model. It includes helpers to
request files with retry semantics and to run batch evaluations either from a
hash list or by searching Hydrus tags. It also exposes a video-processing
batch command which samples frames from GIFs/videos, aggregates per-frame
tags and writes the combined tags back to Hydrus.

The public commands exported to the Click CLI are:

- ``evaluate_api_batch``: process single-frame images (existing behavior)
- ``evaluate_api_batch_video``: process multi-frame content (GIF/video)

most functions in this module use type hints and Sphinx-style docstrings.
"""



from __future__ import annotations

import os
import os.path
import click # pyright: ignore[reportMissingImports]
from PIL import Image, ImageFile, UnidentifiedImageError, ImageChops, ImageStat
from PIL.Image import Image as PILImage
from networkx import lexicographical_topological_sort
from . import interrogate
import hydrus_api
from hydrus_api import APIError
from io import BytesIO
import json
import time
import logging
from datetime import datetime
from typing import Any, Optional, cast, Iterator
import subprocess
import shutil
from pathlib import Path
import gc
import re
import math





# Global settings for PIL
Image.MAX_IMAGE_PIXELS = None
ImageFile.LOAD_TRUNCATED_IMAGES = True



# -----------------------------
# Retry wrapper
# -----------------------------
def get_file_with_retry(client: hydrus_api.Client, file_hash: str, retries: int = 5, delay: int = 5) -> Any:
    """Fetch a file from a Hydrus server with retry semantics.

    The function wraps ``client.get_file`` and will retry transient API
    failures up to ``retries`` times, sleeping ``delay`` seconds between
    attempts. If Hydrus reports a missing file (``FileMissingException``) the
    exception is propagated immediately.

    :param client: Hydrus API client used to fetch files.
    :param file_hash: Hydrus file hash to request.
    :param retries: Number of attempts before giving up.
    :param delay: Seconds to sleep between retry attempts.
    :returns: The response object returned by ``client.get_file``.
    :raises APIError: When Hydrus reports an unrecoverable API error.
    """
    for attempt in range(retries):
        try:
            return client.get_file(file_hash)
        except APIError as e:
            try:
                info = e.response.json()
            except Exception:
                info = {"status_code": getattr(getattr(e, 'response', None), 'status_code', None), "exception_type": None, "text": getattr(getattr(e, 'response', None), 'text', str(e))}

            if info.get("exception_type") == "FileMissingException":
                raise

            if attempt < retries - 1:
                logging.warning(f"retry {attempt} file: {file_hash}")
                time.sleep(delay)
                continue

            logging.error(f"retry fail file: {file_hash}")
            raise



kaomojis: list[str] = [
    "0_0",
    "(o)_(o)",
    "+_+",
    "+_-",
    "._.",
    "<o>_<o>",
    "<|>_<|>",
    "=_=",
    ">_<",
    "3_3",
    "6_9",
    ">_o",
    "@_@",
    "^_^",
    "o_o",
    "u_u",
    "x_x",
    "|_|",
    "||_||",
]



@click.group()
def cli():
    """Top-level Click command group for the WD Hydrus Tagger CLI.

    Commands are registered on this group using :py:meth:`click.Group.add_command`.
    The function body is intentionally empty; Click populates the command
    group at runtime.
    """
    pass



@click.command()
@click.option("--hashfile", help="Text file containing Hydrus hashes")
@click.option("--search-tag", multiple=True,
              help="Hydrus tag(s) to search for (can be used multiple times)")
@click.option("--token", required=True, help="Hydrus API token")
@click.option("--cpu", default=True, help="False to Use GPU instead of CPU")
@click.option("--model", default="wd-eva02-large-tagger-v3",
              help="Tagging model to use")
@click.option("--threshold", default=0.35,
              help="Threshold to drop tags below")
@click.option("--host", default="http://127.0.0.1:45869",
              help="The URL for your Hydrus server ")
@click.option("--tag-service", default="ai tags",
              help="The Hydrus tag service to add tags to")
@click.option("--ratings-only", default=False,
              help="Strip all tags except content rating")
@click.option("--privacy", default=True,
              help="Hide tag output from cli")
@click.option("--debug", is_flag=True, default=False,
              help="Show debug progress and pause before exit")
def evaluate_api_batch(hashfile: Optional[str], search_tag: tuple[str, ...], token: str, cpu: bool,
                       model: str, threshold: float, host: str,
                       tag_service: str, ratings_only: bool, privacy: bool, debug: bool) -> None:
    """Evaluate a batch of single-frame images from Hydrus and add tags.

    This is the existing primary batch command: it either reads file hashes from
    ``hashfile`` or searches Hydrus using ``search_tag`` and applies the
    interrogator to each file, writing tags to the specified Hydrus tag
    service.

    :param hashfile: Optional path to a newline-separated file containing
        Hydrus file hashes to process.
    :param search_tag: One or more Hydrus tags to search for; mutually
        exclusive with ``hashfile``.
    :param token: Hydrus API token for authentication.
    :param cpu: When True, run the interrogator in CPU mode; False to prefer GPU.
    :param model: Local model folder name to load (under ``./model``).
    :param threshold: Minimum tag score threshold to include a tag.
    :param host: URL of the target Hydrus server.
    :param tag_service: Name of the Hydrus tag service to which tags are added.
    :param ratings_only: If True, only the content rating tag is added.
    :param privacy: If True, suppress tag output to the CLI.
    """

    # -----------------------------
    # Setup Logging
    # -----------------------------
    os.makedirs("logs", exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    logfile = f"logs/{model}_{timestamp}.log"

    logging.basicConfig(
        filename=logfile,
        level=logging.INFO,
        format="%(asctime)s - %(message)s"
    )

    logging.info("=== WD HYDRUS TAGGER START ===")
    logging.info(f"Model: {model}")
    logging.info(f"CPU Mode: {cpu}")
    logging.info(f"Tag Service: {tag_service}")

    # -----------------------------
    # Load model info
    # -----------------------------
    if not os.path.isfile('./model/' + model + '/info.json'):
        raise ValueError("info.json not found in model folder!")

    with open('./model/' + model + '/info.json') as json_f:
        modelinfo: dict[str, Any] = json.load(json_f)
        done_hashes_file: str = f"done-hashes-{modelinfo['modelname']}.txt"

    if ratings_only and not modelinfo['ratingsflag']:
        raise ValueError("--ratings-only set, but model does not support ratings!")

    interrogator: interrogate.WaifuDiffusionInterrogator = interrogate.WaifuDiffusionInterrogator(
        modelinfo['modelname'], # the name of the model for display purposes
        modelinfo['modelfile'], # the filename of the model file
        modelinfo['tagsfile'], # the filename of the tags file
        model, # the folder storing the previous two files as well as the info file
		modelinfo['ratingsflag'], # flag indicating whether model identifies content rating
		modelinfo['numberofratings'], # amount of tags to consider for content rating if so
        repo_id=modelinfo['source'], # source of the model, credit where credit is due
    )
    interrogator.load(cpu)

    client: hydrus_api.Client = hydrus_api.Client(token, host)

    # -----------------------------
    # Determine file source
    # -----------------------------
    using_tag_search: bool = False

    if search_tag:
        using_tag_search = True
        #click.echo(f"Searching Hydrus for tags: {search_tag}")
        logging.info(f"Search Tags: {search_tag}")


        # Build a tag list: search tags + system predicate exclusions
        query_tags: list[str] = list(search_tag) + ["system:filetype is not ugoira, video"]
        client.search_files(tags=query_tags)  # warm up the search to avoid first-query lag
        
        hashes: list[str] = cast(list[str], client.search_files(tags=query_tags, return_hashes=True, file_sort_asc=True, file_sort_type=2))


        click.echo(f"Found {len(hashes)} files (excluding ugoira and video).")
        logging.info(f"Found {len(hashes)} files via tag search")

    elif hashfile:
        if not os.path.isfile(hashfile):
            raise ValueError("hashfile not found!")

        with open(hashfile) as f:
            hashes: list[str] = [line.strip() for line in f if line.strip()]

        logging.info(f"Loaded {len(hashes)} hashes from file")

    else:
        raise ValueError("Provide either --search-tag or --hashfile")

    # -----------------------------
    # Done hash tracking (ONLY for hashfile mode)
    # -----------------------------
    done_hashes: set[str] = set()
    bad_hashes: set[str] = set()

    if not using_tag_search:
        if os.path.exists(done_hashes_file):
            with open(done_hashes_file, "r", encoding="utf-8") as f:
                done_hashes = {line.strip() for line in f if line.strip()}

    if os.path.exists("bad-hashes.txt"):
        with open("bad-hashes.txt", "r", encoding="utf-8") as f:
            bad_hashes = {line.strip() for line in f if line.strip()}

    # -----------------------------
    # Processing Loop
    # -----------------------------
    processed_count = 0
    interrupted = False

    counterh = 1
    totalh = len(hashes)
    
    def _show_idh(item) -> str:
        return f"{counterh}/{totalh}"


    try:
        with click.progressbar(hashes, item_show_func=_show_idh) as bar:
            for file_hash in bar:
                counterh += 1

                file_hash = str(file_hash)

                if not file_hash or file_hash in bad_hashes:
                    continue

                if not using_tag_search and file_hash in done_hashes:
                    continue

                click.echo("\nprocessing: " + file_hash)
                logging.info(f"Processing: {file_hash}")

                try:
                    response: Any = get_file_with_retry(client, file_hash)

                except hydrus_api.APIError as e:
                    try:
                        info = e.response.json()
                    except Exception:
                        info = {"status_code": getattr(getattr(e, 'response', None), 'status_code', None), "exception_type": None, "text": getattr(getattr(e, 'response', None), 'text', str(e))}
                    status = info.get("status_code")
                    etype = info.get("exception_type")
                    click.echo(f"Hydrus error {status} ({etype}) on {file_hash}")
                    logging.warning(f"Hydrus error {status} ({etype}) on {file_hash}")

                    if etype == "FileMissingException":
                        click.echo(f"Added to bad-hashes.txt: {file_hash}")
                        bad_hashes.add(file_hash)
                        with open("bad-hashes.txt", "a", encoding="utf-8") as bad_f:
                            bad_f.write(file_hash + "\n")
                        continue
                    else:
                        # real error, not a bad hash
                        raise
                except RuntimeError as e:
                    click.echo(str(e))
                    click.echo("Hydrus seems unreachable — stopping batch.")
                    logging.error(str(e))
                    logging.error("Hydrus seems unreachable — stopping batch.")
                    raise
                image_bytes: BytesIO = BytesIO(response.content)

                try:
                    image: PILImage = Image.open(image_bytes)
                    image = image.convert("RGB").resize((448, 448))
                except (UnidentifiedImageError, OSError):
                    click.echo(f"Skipping unreadable or non-image file: {file_hash}")
                    logging.warning(f"Skipping unreadable or non-image file: {file_hash}")
                    bad_hashes.add(file_hash)
                    with open("bad-hashes.txt", "a", encoding="utf-8") as bad_f:
                        bad_f.write(file_hash + "\n")
                    continue

                ratings: dict[str, float]
                tags: dict[str, float]
                ratings, tags = interrogator.interrogate(image)  # pyright: ignore[reportArgumentType]

                rating: str = "none"
                if modelinfo['ratingsflag']:
                    ratings["none"] = 0.0
                    for key in ratings.keys():
                        if ratings[key] > ratings[rating]:
                            rating = key

                clipped_tags: list[str] = []

                if not ratings_only:
                    for key in tags.keys():
                        if tags[key] > threshold:
                            clipped_tags.append(
                                key.replace("_", " ") if key not in kaomojis else key
                            )
                if not privacy:
                    click.echo("rating: " + rating)
                    click.echo("tags: " + ", ".join(clipped_tags))
                    click.echo()

                if modelinfo['ratingsflag']:
                    clipped_tags.append("rating:" + rating)

                if ratings_only:
                    clipped_tags.append(
                        "ratings only " + modelinfo['modelname'] + " ai generated tags"
                    )
                else:
                    clipped_tags.append(
                        modelinfo['modelname'] + " ai generated tags"
                    )

                client.add_tags(
                    hashes=[file_hash],
                    service_names_to_tags={tag_service: clipped_tags} # pyright: ignore[reportCallIssue]
                )

                processed_count += 1

                # Only write done-hash if using hashfile mode
                if not using_tag_search:
                    done_hashes.add(file_hash)
                    with open(done_hashes_file, "a", encoding="utf-8") as done_f:
                        done_f.write(file_hash + "\n")

                # --- Micro pause: let tag write commit ---
                time.sleep(0.1)
                # --- Macro pause: only every 200 files ---
                if processed_count % 200 == 0:
                    time.sleep(3)
                    logging.info(f"Processed {processed_count} files")

    except KeyboardInterrupt:
        interrupted = True
        click.echo("\n[!] Interrupted by user (Ctrl+C)")
        logging.warning("=== INTERRUPTED BY USER (CTRL+C) ===")

    finally:
        logging.info("=== WD HYDRUS TAGGER FINISHED ===")
        logging.info(f"Total processed: {processed_count}")

        if interrupted:
            logging.info("Run ended due to manual interruption.")
        else:
            logging.info("Run completed normally.")

        logging.shutdown()

        click.echo(f"\nFinished. Total processed: {processed_count}")

        if debug:
            try:
                click.echo("Debug mode: press Enter to exit.")
                input()
            except Exception:
                # If stdin is not available, ignore and continue exiting
                pass




def process_frames_streaming(
    frame_generator: Iterator[PILImage],
    interrogator,
    client,
    file_hash: str,
    similarity_threshold: float,
    threshold: float,
    ratingsflag: bool,
):
    """
    True streaming frame processor with live progress bar.
    No frame list is stored.
    """

    agg_scores: dict[str, float] = {}
    agg_ratings: dict[str, float] = {}

    last_small: Optional[PILImage] = None
    kept_count = 0
    total_count = 0

    # Get total frames from API
    metadata = client.get_file_metadata(hashes=[file_hash])
    total_video_frames = metadata[0].get('num_frames', 0)

    with click.progressbar(
        frame_generator,
        length=total_video_frames,
        label="Filtering & Tagging Frames",
        show_pos=False, # We disable show_pos because we are showing it in item_show_func
        item_show_func=lambda _: f"Frame:{total_count}/{total_video_frames} Tagged:{kept_count}"
    ) as bar:

        for img in bar:
            total_count += 1
            # Update the bar text every iteration
            bar.update(0) 

            # similarity check
            small = img.resize((64, 64)).convert("L")

            keep_frame = False
            if last_small is None:
                keep_frame = True
            else:
                diff = ImageChops.difference(small, last_small)
                stat = ImageStat.Stat(diff)
                mean_diff = sum(stat.mean) / len(stat.mean)
                if mean_diff >= similarity_threshold:
                    keep_frame = True

            if not keep_frame:
                img.close()
                continue

            # Frame is being kept/tagged
            kept_count += 1
            last_small = small

            ratings, tags = interrogator.interrogate(img)

            for t, s in tags.items():
                score = float(s)
                if score > threshold:
                    agg_scores[t] = max(agg_scores.get(t, 0.0), score)

            if ratingsflag:
                for r, s in ratings.items():
                    score = float(s)
                    if score > threshold:
                        agg_ratings[r] = max(agg_ratings.get(r, 0.0), score)

            img.close()

    return agg_scores, agg_ratings, kept_count, total_count



@click.command()
@click.option("--hashfile", help="Text file containing Hydrus hashes")
@click.option("--search-tag", multiple=True,
              help="Hydrus tag(s) to search for (can be used multiple times)")
@click.option("--token", required=True, help="Hydrus API token")
@click.option("--cpu", default=True, help="False to Use GPU instead of CPU")
@click.option("--model", default="wd-eva02-large-tagger-v3",
              help="Tagging model to use")
@click.option("--threshold", default=0.35,
              help="Threshold to drop tags below")
@click.option("--host", default="http://127.0.0.1:45869",
              help="The URL for your Hydrus server ")
@click.option("--tag-service", default="ai tags",
              help="The Hydrus tag service to add tags to")
@click.option("--ratings-only", default=False,
              help="Strip all tags except content rating")
@click.option("--privacy", default=True,
              help="Hide tag output from cli")
@click.option("--debug", is_flag=True, default=False,
              help="Show debug progress for video processing")
def evaluate_api_batch_video(hashfile: Optional[str], search_tag: tuple[str, ...], token: str, cpu: bool,
                             model: str, threshold: float, host: str,
                             tag_service: str, ratings_only: bool, privacy: bool, debug: bool) -> None:
    """Evaluate a batch of multi-frame content (GIF/video) and apply tags with RAM optimization.

    This command is similar to :func:`evaluate_api_batch` but targets
    multi-frame content. For animated GIFs the frames are read via PIL; for
    other video containers the function will attempt to use ``ffmpeg`` (if
    available) to extract one frame per second. Frames are dynamically
    filtered for similarity before interrogation for efficiency.

    The per-frame tag scores are aggregated (averaged) and the resulting tag
    list is applied to the original video file in Hydrus.

    :param hashfile: Optional path to a newline-separated file containing
        Hydrus file hashes to process.
    :param search_tag: One or more Hydrus tags to search for; mutually
        exclusive with ``hashfile``.
    :param token: Hydrus API token for authentication.
    :param cpu: When True, run the interrogator in CPU mode; False to prefer GPU.
    :param model: Local model folder name to load (under ``./model``).
    :param threshold: Minimum tag score threshold to include a tag.
    :param host: URL of the target Hydrus server.
    :param tag_service: Name of the Hydrus tag service to which tags are added.
    :param ratings_only: If True, only the content rating tag is added.
    :param privacy: If True, suppress tag output to the CLI.
    """

    # Setup logging and model like the image batch command
    os.makedirs("logs", exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    logfile = f"logs/{model}_{timestamp}.log"

    logging.basicConfig(
        filename=logfile,
        level=logging.INFO,
        format="%(asctime)s - %(message)s"
    )

    logging.info("=== WD HYDRUS VIDEO TAGGER START ===")
    logging.info(f"Model: {model}")
    logging.info(f"CPU Mode: {cpu}")
    logging.info(f"Tag Service: {tag_service}")

    # Clean up repository-local ffmpeg temporary files from previous runs
    try:
        repo_root = Path(__file__).resolve().parents[1]
        repo_tmp_dir = repo_root / "ffmpeg_temp"
        if repo_tmp_dir.exists():
            for p in repo_tmp_dir.iterdir():
                try:
                    # Delete only folders starting with "deleted_"
                    if p.is_dir() and p.name.startswith("deleted_"):
                        shutil.rmtree(p)
                     # Delete only files matching "frame_*.jpg"
                    elif p.is_file() and p.name.startswith("frame_") and p.suffix == ".jpg":
                        p.unlink()
                except Exception:
                    # ignore individual cleanup errors
                    pass
    except Exception:
        logging.exception("Failed to clean ffmpeg_temp at startup")
        

    if not os.path.isfile('./model/' + model + '/info.json'):
        raise ValueError("info.json not found in model folder!")

    with open('./model/' + model + '/info.json') as json_f:
        modelinfo: dict[str, Any] = json.load(json_f)
        done_hashes_file: str = f"done-hashes-{modelinfo['modelname']}.txt"

    if ratings_only and not modelinfo['ratingsflag']:
        raise ValueError("--ratings-only set, but model does not support ratings!")

    interrogator: interrogate.WaifuDiffusionInterrogator = interrogate.WaifuDiffusionInterrogator(
        modelinfo['modelname'], # the name of the model for display purposes
        modelinfo['modelfile'], # the filename of the model file
        modelinfo['tagsfile'], # the filename of the tags file
        model, # the folder storing the previous two files as well as the info file
		modelinfo['ratingsflag'], # flag indicating whether model identifies content rating
		modelinfo['numberofratings'], # amount of tags to consider for content rating if so
        repo_id=modelinfo['source'], # source of the model, credit where credit is due
    )
    interrogator.load(cpu)

    client: hydrus_api.Client = hydrus_api.Client(token, host)

    # Determine file source (search for video content)
    using_tag_search: bool = False

    if search_tag:
        using_tag_search = True
        logging.info(f"Search Tags: {search_tag}")
        # Include only animated/video types not images
        query_tags: list[str] = list(search_tag) + ["system:filetype is ugoira, video"]


        client.search_files(tags=query_tags)
        hashes: list[str] = cast(list[str], client.search_files(tags=query_tags, return_hashes=True, file_sort_asc=True, file_sort_type=16))
        # sort type 16 is "system:number of frames", which should help with processing efficiency by front-loading shorter videos.

        click.echo(f"Found {len(hashes)} files (animated/video).")
        logging.info(f"Found {len(hashes)} files via tag search")

    elif hashfile:
        if not os.path.isfile(hashfile):
            raise ValueError("hashfile not found!")
        with open(hashfile) as f:
            hashes: list[str] = [line.strip() for line in f if line.strip()]
        logging.info(f"Loaded {len(hashes)} hashes from file")
    else:
        raise ValueError("Provide either --search-tag or --hashfile")

    done_hashes: set[str] = set()
    bad_hashes: set[str] = set()

    if not using_tag_search:
        if os.path.exists(done_hashes_file):
            with open(done_hashes_file, "r", encoding="utf-8") as f:
                done_hashes = {line.strip() for line in f if line.strip()}

    if os.path.exists("bad-hashes.txt"):
        with open("bad-hashes.txt", "r", encoding="utf-8") as f:
            bad_hashes = {line.strip() for line in f if line.strip()}


    processed_count = 0
    interrupted = False

    counterh = 0
    totalh = len(hashes)
    
    def _show_idh(item) -> str:
        return f"{counterh}/{totalh} Done"

    try:
        with click.progressbar(hashes, item_show_func=_show_idh) as bar:
            for file_hash in bar:
                counterh += 1

                file_hash = str(file_hash)

                if not file_hash or file_hash in bad_hashes:
                    continue

                if not using_tag_search and file_hash in done_hashes:
                    continue


                metadata = client.get_file_metadata(hashes=[file_hash])
                # Use 'or 0' to catch cases where the key is missing OR the value is None
                num_frames = metadata[0].get('num_frames') or 0
                total_video_duration = metadata[0].get('duration') or 0

                # Now it is safe to log and process
                #logging.info(f"Metadata received: {metadata}")

                def dynamic_threshold(total_video_frames: float, total_video_duration: float) -> float:
                    duration_seconds = total_video_duration / 1000.0
                    fps = total_video_frames / duration_seconds if duration_seconds > 0 else 30.0

                    base = 0.75 * math.log(total_video_frames) - 4.0
                    fps_adjust = 0.15 * math.log(max(fps, 1))

                    t = base + fps_adjust
                    return max(2.0, min(t, 50.0))

                similarity_threshold_ff = 12.0
                similarity_threshold_ff = dynamic_threshold(num_frames, total_video_duration)

                if num_frames:
                    click.echo(f"\n  Processing {num_frames} frames for hash {file_hash}")
                    logging.info(f"Processing {num_frames} frames for hash {file_hash}")
                    click.echo(f"  Similarity threshold > {similarity_threshold_ff:.2f}")
                    logging.info(f"Similarity threshold > {similarity_threshold_ff:.2f}")
                else:
                    click.echo(f"\n  File {file_hash} is a static image or has no frame count.")
                    logging.info(f"File {file_hash} is a static image or has no frame count.")
                    click.echo(f"  Similarity threshold > {similarity_threshold_ff:.2f}")
                    logging.info(f"Similarity threshold > {similarity_threshold_ff:.2f}")


                try:
                    click.echo(f"  [INFO] Fetching video from Hydrus: {file_hash}")
                    response: Any = get_file_with_retry(client, file_hash)

                except hydrus_api.APIError as e:
                    info = e.response.json()
                    status = info.get("status_code")
                    etype = info.get("exception_type")
                    click.echo(f"Hydrus error {status} ({etype}) on {file_hash}")
                    logging.warning(f"Hydrus error {status} ({etype}) on {file_hash}")

                    if etype == "FileMissingException":
                        click.echo(f"Added to bad-hashes.txt: {file_hash}")
                        bad_hashes.add(file_hash)
                        with open("bad-hashes.txt", "a", encoding="utf-8") as bad_f:
                            bad_f.write(file_hash + "\n")
                        continue
                    else:
                        raise
                except RuntimeError as e:
                    click.echo(str(e))
                    click.echo("Hydrus seems unreachable — stopping batch.")
                    logging.error(str(e))
                    logging.error("Hydrus seems unreachable — stopping batch.")
                    raise

                # --- Frame Generators for RAM Efficiency ---
                def pil_frame_gen(data: bytes):
                    count = 0
                    with Image.open(BytesIO(data)) as container:
                        n = getattr(container, "n_frames", 1)
                        for i in range(n):
                            container.seek(i)
                            count += 1
                            yield container.convert("RGB").resize((448, 448))
                    logging.info(f"[pil] Total frames extracted: {count} for {file_hash}")

                
                def ffmpeg_frame_gen(data: bytes, h: str, tmp_dir: Path):
                    count = 0
                    in_path = tmp_dir / f"vid_{h}"
                    in_path.write_bytes(data)
                    out_pattern = str(tmp_dir / f"frame_{h}_%05d.jpg")
                    
                    repo_root = Path(__file__).resolve().parents[1]
                    bundled_ffmpeg = repo_root / "ffmpeg" / "bin" / ("ffmpeg.exe" if os.name == "nt" else "ffmpeg")
                    ffmpeg_exe = str(bundled_ffmpeg) if bundled_ffmpeg.exists() else "ffmpeg"

                    subprocess.run([ffmpeg_exe, "-y", "-i", str(in_path), 
                                    "-vf", "scale=448:448:force_original_aspect_ratio=decrease,pad=448:448:(ow-iw)/2:(oh-ih)/2", 
                                    "-fps_mode", "passthrough", 
                                    "-q:v", "2", 
                                    out_pattern],
                                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False)
                    
                    for p in sorted(tmp_dir.glob(f"frame_{h}_*.jpg")):
                        with Image.open(p) as f_img:
                            count += 1
                            yield f_img.convert("RGB")
                        p.unlink()
                    if in_path.exists(): in_path.unlink()
                    logging.info(f"[ffmpeg] Total frames extracted: {count} for {file_hash}")

                repo_root = Path(__file__).resolve().parents[1]
                repo_tmp_dir = repo_root / "ffmpeg_temp"
                repo_tmp_dir.mkdir(parents=True, exist_ok=True)

                click.echo("  [INFO] Preparation complete.")

                try:
                    # Test open once to verify it is PIL-compatible
                    test_img = Image.open(BytesIO(response.content))
                    test_img.close()
                    frame_gen = pil_frame_gen(response.content)
                except UnidentifiedImageError:
                    # Not an image container > use ffmpeg
                    frame_gen = ffmpeg_frame_gen(response.content, file_hash, repo_tmp_dir)

                agg_scores, agg_ratings, kept_frames, total_frames = process_frames_streaming(
                    frame_generator=frame_gen,
                    interrogator=interrogator,
                    client=client,
                    file_hash=file_hash,
                    similarity_threshold=similarity_threshold_ff,
                    threshold=threshold,
                    ratingsflag=modelinfo['ratingsflag'],
                )


                click.echo(f"Kept and tagged {kept_frames} of {total_frames} frames")
                logging.info(f"Kept and tagged {kept_frames} of {total_frames} frames for {file_hash}")
                click.echo()

                rating_priority = {
                "explicit": 4,
                "questionable": 3,
                "sensitive": 2,
                "general": 1,
                "none": 0
                }


                rating = "none"
                if modelinfo['ratingsflag']:
                    agg_ratings.setdefault("none", 0.0)
                    for r, score in agg_ratings.items():
                        if score > threshold and rating_priority.get(r, 0) > rating_priority.get(rating, 0):
                            rating = r


                clipped_tags = [k.replace("_", " ") if k not in kaomojis else k for k, v in agg_scores.items() if v > threshold]

                if not privacy:
                    click.echo("rating: " + rating)
                    click.echo("tags: " + ", ".join(clipped_tags))
                    click.echo()

                if modelinfo['ratingsflag']:
                    clipped_tags.append("rating:" + rating)

                
                clipped_tags.append(f"{modelinfo['modelname']} ai generated tags")


                client.add_tags(
                    hashes=[file_hash], 
                    service_names_to_tags={tag_service: clipped_tags})

                processed_count += 1
                gc.collect()


                if not using_tag_search:
                    done_hashes.add(file_hash)
                    with open(done_hashes_file, "a", encoding="utf-8") as done_f:
                        done_f.write(file_hash + "\n")

                time.sleep(0.1)

                if processed_count % 10 == 0:
                    time.sleep(3)
                    logging.info(f"Processed {processed_count} files")

    except KeyboardInterrupt:
        interrupted = True
        click.echo("\n[!] Interrupted by user (Ctrl+C)")
        logging.warning("=== INTERRUPTED BY USER (CTRL+C) ===")

    finally:
        logging.info("=== WD HYDRUS VIDEO TAGGER FINISHED ===")
        logging.info(f"Total processed: {processed_count}")

        if interrupted:
            logging.info("Run ended due to manual interruption.")
        else:
            logging.info("Run completed normally.")

        logging.shutdown()

        click.echo(f"\nFinished. Total processed: {processed_count}")

        if debug:
            try:
                click.echo("Debug mode: press Enter to exit.")
                input()
            except Exception:
                # If stdin is not available, ignore and continue exiting
                pass



@click.command(name="video_similarity_calibration")
@click.option("--file-hash", help="Hydrus file hash to fetch (mutually exclusive with --local-file)")
@click.option("--local-file", help="Path to a local video file (mutually exclusive with --file-hash)")
@click.option("--token", help="Hydrus API token (required if --file-hash used)")
@click.option("--host", default="http://127.0.0.1:45869", help="Hydrus host (used with --file-hash)")
@click.option("--similarity", default="10.0,9.0,8.0,7.0,6.0,5.0,4.0,3.0,2.0,1.0", help="Comma-separated similarity thresholds to test, e.g. '10.0,9.0,8.0'")
@click.option("--max-frames", default=0, type=int, help="Maximum frames to keep per threshold (0 = unlimited)")
@click.option("--no-cache", is_flag=True, default=False, help="Store 64x64 frames on disk instead of RAM")
@click.option("--debug", is_flag=True, default=False, help="Show debug output and keep extracted frames")
def video_similarity_calibration(
    file_hash: Optional[str],
    local_file: Optional[str],
    token: Optional[str],
    host: str,
    similarity: str,
    max_frames: int,
    no_cache: bool,
    debug: bool
) -> None:
    # --- State Variables ---
    processed_count = 0
    interrupted = False
    client = None
    total_video_frames = 0
    content_bytes: bytes = b""
    label: str = ""
    is_pil = False
    
    ram_cache: list[PILImage] = []

    repo_root = Path(__file__).resolve().parents[1]
    repo_tmp_dir = repo_root / "ffmpeg_temp"
    # NEU: Ein eigener Ordner nur für die Text-Zusammenfassungen
    results_dir = repo_root / "summary_results" 
    
    repo_tmp_dir.mkdir(parents=True, exist_ok=True)
    results_dir.mkdir(parents=True, exist_ok=True)

    # 0. Datenquelle identifizieren
    if file_hash:
        label = file_hash
    elif local_file:
        p = Path(local_file)
        if not p.exists():
            click.echo(f"[ERROR] Local file not found: {local_file}")
            return
        label = p.stem
        total_video_frames = 0 # Wird bei Videos später durch FFmpeg/Prob erkannt falls nötig
    else:
        raise ValueError("Provide --file-hash or --local-file")

    summary_file = results_dir / f"summary_{label}.txt"

    # 1. Bestehende Summary prüfen (Resume Logik)
    already_tested = {}
    if summary_file.exists():
        click.echo(f"[INFO] Summary file found. Checking progress...")
        with open(summary_file, "r", encoding="utf-8") as rf:
            content = rf.read()
            # Suche alle bereits fertigen Thresholds
            matches = re.findall(r"Threshold\s+([0-9.]+):\s+selected\s+([0-9]+)", content)
            for thr_str, sel_str in matches:
                already_tested[float(thr_str)] = int(sel_str)
        
        # Abbruch falls der letzte Test bereits <= 1 Frame ergab
        if already_tested:
            last_thr = list(already_tested.keys())[-1]
            if already_tested[last_thr] <= 1:
                click.echo(f"[INFO] Last result for Thr {last_thr} was <= 1. Already finished.")
                return


    try:
        # 2. Datenquelle identifizieren
        if file_hash:
            client = hydrus_api.Client(token, host)
            try:
                metadata = client.get_file_metadata(hashes=[file_hash])
                total_video_frames = metadata[0].get('num_frames', 0)
                click.echo(f"[INFO] Fetching video from Hydrus: {file_hash}")
                response = get_file_with_retry(client, file_hash)
                content_bytes = response.content
                label = file_hash
            except Exception as e:
                click.echo(f"Error fetching from Hydrus: {e}")
                return
        elif local_file:
            p = Path(local_file)
            if not p.exists():
                click.echo(f"[ERROR] Local file not found: {local_file}")
                return
            content_bytes = p.read_bytes()
            label = p.stem
            total_video_frames = 0 # Wird bei Videos später durch FFmpeg/Prob erkannt falls nötig
        else:
            raise ValueError("Provide --file-hash or --local-file")


        # Header nur schreiben wenn Datei neu ist
        if not summary_file.exists():
            with open(summary_file, "w", encoding="utf-8") as sf:
                sf.write(f"Calibration for: {label}\n")
                sf.write(f"Total File frames: {total_video_frames}\n")
                sf.write("-" * 30 + "\n")

        # 3. Medien-Typ prüfen
        try:
            with Image.open(BytesIO(content_bytes)):
                is_pil = True
        except UnidentifiedImageError:
            is_pil = False

        # 4. Vorbereitung (FFmpeg oder PIL Extraktion)
        if not is_pil:
            click.echo(f"[INFO] Video detected. Extracting 64x64 thumbnails via FFmpeg...")
            in_path = repo_tmp_dir / f"vid_{label}"
            in_path.write_bytes(content_bytes)
            
            bundled_ffmpeg = repo_root / "ffmpeg" / "bin" / ("ffmpeg.exe" if os.name == "nt" else "ffmpeg")
            ffmpeg_exe = str(bundled_ffmpeg) if bundled_ffmpeg.exists() else "ffmpeg"

            out_pattern = str(repo_tmp_dir / f"small_{label}_%05d.jpg")
            subprocess.run([
                ffmpeg_exe, "-y", "-i", str(in_path), 
                "-vf", "scale=64:64,format=gray", 
                "-q:v", "4", 
                out_pattern
            ], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False)
            
            if in_path.exists(): in_path.unlink()

            if not no_cache:
                click.echo("[INFO] Caching thumbnails to RAM...")
                temp_files = sorted(repo_tmp_dir.glob(f"small_{label}_*.jpg"))
                for p in temp_files:
                    with Image.open(p) as tmp_img:
                        ram_cache.append(tmp_img.copy())
                    p.unlink()
            
            click.echo("[INFO] Preparation complete.")
        else:
            with Image.open(BytesIO(content_bytes)) as container:
                for i in range(getattr(container, "n_frames", 1)):
                    container.seek(i)
                    small = container.convert("L").resize((64, 64))
                    ram_cache.append(small)

        # 5. Calibration Loop
        similarity_list = [float(s.strip()) for s in similarity.split(",") if s.strip()]

        for thr in similarity_list:
            if thr in already_tested:
                click.echo(f"[SKIP] Threshold {thr} already processed (selected {already_tested[thr]}).")
                continue

            click.echo(f"\n[TESTING] Similarity Threshold: {thr}")
            
            if no_cache and not is_pil:
                source_files = sorted(repo_tmp_dir.glob(f"small_{label}_*.jpg"))
                frame_gen = (Image.open(p) for p in source_files)
                total_len = len(source_files)
            else:
                frame_gen = iter(ram_cache)
                total_len = len(ram_cache)

            current_total = 0
            current_kept = 0
            last_small = None

            def progress_label(item):
                return f"Frame:{current_total}/{total_len} Kept:{current_kept}"

            with click.progressbar(
                frame_gen,
                length=total_len,
                label=f"(Thr {thr})",
                item_show_func=progress_label
            ) as bar:
                for small_img in bar:
                    current_total += 1
                    bar.update(0)

                    keep = False
                    if last_small is None:
                        keep = True
                    else:
                        diff = ImageChops.difference(small_img, last_small)
                        stat = ImageStat.Stat(diff)
                        mean_diff = sum(stat.mean) / len(stat.mean)
                        if mean_diff >= thr:
                            keep = True

                    if keep:
                        current_kept += 1
                        last_small = small_img.copy() if no_cache else small_img
                        if max_frames > 0 and current_kept >= max_frames:
                            break
                    
                    if no_cache: small_img.close()

            # Ergebnis speichern
            with open(summary_file, "a", encoding="utf-8") as sf:
                sf.write(f"Threshold {thr}: selected {current_kept} frames (from {current_total})\n")

            click.echo(f"[RESULT] Threshold {thr}: {current_kept} frames selected.")
            processed_count += 1
            
            # Wenn nur noch 1 Frame übrig ist (der erste), macht weitermachen keinen Sinn
            if current_kept <= 1:
                click.echo("[INFO] Stop: Threshold too high (selected <= 1).")
                break

    except KeyboardInterrupt:
        interrupted = True
        click.echo("\n[!] Interrupted by user (Ctrl+C)")
    except Exception as e:
        click.echo(f"\n[ERROR] {e}")
    finally:
        if no_cache:
            click.echo("[INFO] Cleaning up 64x64 cache frames...")
            for p in repo_tmp_dir.glob(f"small_{label}_*.jpg"):
                try: p.unlink()
                except Exception: pass

        logging.shutdown()
        click.echo(f"\nFinished. New thresholds processed: {processed_count}")

        if debug:
            try:
                click.echo("Debug mode: press Enter to exit.")
                input()
            except Exception: pass


if __name__ == '__main__':
    Image.init()
    ImageFile.LOAD_TRUNCATED_IMAGES = True
    cli.add_command(evaluate_api_batch) # pyright: ignore[reportFunctionMemberAccess]
    cli.add_command(evaluate_api_batch_video) # pyright: ignore[reportFunctionMemberAccess]
    cli.add_command(video_similarity_calibration) # pyright: ignore[reportFunctionMemberAccess]
    cli()

