"""Command-line entrypoint for the WD Hydrus Tagger utility.

This module provides a Click-based CLI that queries a Hydrus server for files
and applies tags generated by a local tagging model. It includes helpers to
request files with retry semantics and to run batch evaluations either from a
hash list or by searching Hydrus tags. It also exposes a video-processing
batch command which samples frames from GIFs/videos, aggregates per-frame
tags and writes the combined tags back to Hydrus.

The public commands exported to the Click CLI are:

- ``evaluate_api_batch``: process single-frame images (existing behavior)
- ``evaluate_api_batch_video``: process multi-frame content (GIF/video)

most functions in this module use type hints and Sphinx-style docstrings.
"""



from __future__ import annotations

from math import log
import os
import os.path
import click # pyright: ignore[reportMissingImports]
from PIL import Image, ImageFile, UnidentifiedImageError, ImageChops, ImageStat
from PIL.Image import Image as PILImage
from . import interrogate
import hydrus_api
from hydrus_api import APIError
from io import BytesIO
import json
import time
import logging
from datetime import datetime
from typing import Any, Optional, cast, Iterator
import subprocess
import shutil
from pathlib import Path
from itertools import count

import gc





# The memory_profiler import and setup is included here in the main module so that it can be used across all commands, 
# including the video batch command which is where memory usage is more of a concern. 
# The memory_profiler will log detailed memory usage information to a timestamped log file in the logs directory, 
# which can be reviewed after running the commands to analyze memory behavior and identify potential issues.

# @profile(stream=memory_profiler_logg) decorators are added to all functions even if they are not expected to have significant memory usage, 
# to provide a complete picture of memory behavior across the entire execution of the commands.
try:
    from memory_profiler import profile # pyright: ignore[reportAssignmentType]
except ImportError:
    def profile(stream=None):
        return lambda f: f
    
# Logging Setup for memory profiler (separate from the main logging used for command progress and info)
os.makedirs("logs", exist_ok=True)
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
memory_profiler_logg_shrug = f"logs/memory_profiler_{timestamp}.log"
memory_profiler_logg = open(memory_profiler_logg_shrug, "w")  # Open the log file for writing memory profiler output


# Global settings for PIL
Image.MAX_IMAGE_PIXELS = None
ImageFile.LOAD_TRUNCATED_IMAGES = True


# -----------------------------
# Retry wrapper
# -----------------------------
@profile(stream=memory_profiler_logg)
def get_file_with_retry(client: hydrus_api.Client, file_hash: str, retries: int = 5, delay: int = 5) -> Any:
    """Fetch a file from a Hydrus server with retry semantics.

    The function wraps ``client.get_file`` and will retry transient API
    failures up to ``retries`` times, sleeping ``delay`` seconds between
    attempts. If Hydrus reports a missing file (``FileMissingException``) the
    exception is propagated immediately.

    :param client: Hydrus API client used to fetch files.
    :param file_hash: Hydrus file hash to request.
    :param retries: Number of attempts before giving up.
    :param delay: Seconds to sleep between retry attempts.
    :returns: The response object returned by ``client.get_file``.
    :raises APIError: When Hydrus reports an unrecoverable API error.
    """
    for attempt in range(retries):
        try:
            return client.get_file(file_hash)
        except APIError as e:
            try:
                info = e.response.json()
            except Exception:
                info = {"status_code": getattr(getattr(e, 'response', None), 'status_code', None), "exception_type": None, "text": getattr(getattr(e, 'response', None), 'text', str(e))}

            if info.get("exception_type") == "FileMissingException":
                raise

            if attempt < retries - 1:
                logging.warning(f"retry {attempt} file: {file_hash}")
                time.sleep(delay)
                continue

            logging.error(f"retry fail file: {file_hash}")
            raise


kaomojis: list[str] = [
    "0_0",
    "(o)_(o)",
    "+_+",
    "+_-",
    "._.",
    "<o>_<o>",
    "<|>_<|>",
    "=_=",
    ">_<",
    "3_3",
    "6_9",
    ">_o",
    "@_@",
    "^_^",
    "o_o",
    "u_u",
    "x_x",
    "|_|",
    "||_||",
]


@click.group()
@profile(stream=memory_profiler_logg)
def cli():
    """Top-level Click command group for the WD Hydrus Tagger CLI.

    Commands are registered on this group using :py:meth:`click.Group.add_command`.
    The function body is intentionally empty; Click populates the command
    group at runtime.
    """
    pass


@click.command()
@click.option("--hashfile", help="Text file containing Hydrus hashes")
@click.option("--search-tag", multiple=True,
              help="Hydrus tag(s) to search for (can be used multiple times)")
@click.option("--token", required=True, help="Hydrus API token")
@click.option("--cpu", default=True, help="False to Use GPU instead of CPU")
@click.option("--model", default="wd-eva02-large-tagger-v3",
              help="Tagging model to use")
@click.option("--threshold", default=0.35,
              help="Threshold to drop tags below")
@click.option("--host", default="http://127.0.0.1:45869",
              help="The URL for your Hydrus server ")
@click.option("--tag-service", default="ai tags",
              help="The Hydrus tag service to add tags to")
@click.option("--ratings-only", default=False,
              help="Strip all tags except content rating")
@click.option("--privacy", default=True,
              help="Hide tag output from cli")
@click.option("--debug", is_flag=True, default=False,
              help="Show debug progress and pause before exit")
@profile(stream=memory_profiler_logg)
def evaluate_api_batch(hashfile: Optional[str], search_tag: tuple[str, ...], token: str, cpu: bool,
                       model: str, threshold: float, host: str,
                       tag_service: str, ratings_only: bool, privacy: bool, debug: bool) -> None:
    """Evaluate a batch of single-frame images from Hydrus and add tags.

    This is the existing primary batch command: it either reads file hashes from
    ``hashfile`` or searches Hydrus using ``search_tag`` and applies the
    interrogator to each file, writing tags to the specified Hydrus tag
    service.

    :param hashfile: Optional path to a newline-separated file containing
        Hydrus file hashes to process.
    :param search_tag: One or more Hydrus tags to search for; mutually
        exclusive with ``hashfile``.
    :param token: Hydrus API token for authentication.
    :param cpu: When True, run the interrogator in CPU mode; False to prefer GPU.
    :param model: Local model folder name to load (under ``./model``).
    :param threshold: Minimum tag score threshold to include a tag.
    :param host: URL of the target Hydrus server.
    :param tag_service: Name of the Hydrus tag service to which tags are added.
    :param ratings_only: If True, only the content rating tag is added.
    :param privacy: If True, suppress tag output to the CLI.
    """

    # -----------------------------
    # Setup Logging
    # -----------------------------
    os.makedirs("logs", exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    logfile = f"logs/{model}_{timestamp}.log"

    logging.basicConfig(
        filename=logfile,
        level=logging.INFO,
        format="%(asctime)s - %(message)s"
    )

    logging.info("=== WD HYDRUS TAGGER START ===")
    logging.info(f"Model: {model}")
    logging.info(f"CPU Mode: {cpu}")
    logging.info(f"Tag Service: {tag_service}")

    # -----------------------------
    # Load model info
    # -----------------------------
    if not os.path.isfile('./model/' + model + '/info.json'):
        raise ValueError("info.json not found in model folder!")

    with open('./model/' + model + '/info.json') as json_f:
        modelinfo: dict[str, Any] = json.load(json_f)
        done_hashes_file: str = f"done-hashes-{modelinfo['modelname']}.txt"

    if ratings_only and not modelinfo['ratingsflag']:
        raise ValueError("--ratings-only set, but model does not support ratings!")

    interrogator: interrogate.WaifuDiffusionInterrogator = interrogate.WaifuDiffusionInterrogator(
        modelinfo['modelname'], # the name of the model for display purposes
        modelinfo['modelfile'], # the filename of the model file
        modelinfo['tagsfile'], # the filename of the tags file
        model, # the folder storing the previous two files as well as the info file
		modelinfo['ratingsflag'], # flag indicating whether model identifies content rating
		modelinfo['numberofratings'], # amount of tags to consider for content rating if so
        repo_id=modelinfo['source'], # source of the model, credit where credit is due
    )
    interrogator.load(cpu)

    client: hydrus_api.Client = hydrus_api.Client(token, host)

    # -----------------------------
    # Determine file source
    # -----------------------------
    using_tag_search: bool = False

    if search_tag:
        using_tag_search = True
        #click.echo(f"Searching Hydrus for tags: {search_tag}")
        logging.info(f"Search Tags: {search_tag}")


        # Build a tag list: search tags + system predicate exclusions
        query_tags: list[str] = list(search_tag) + ["system:filetype is not ugoira, video"]
        client.search_files(tags=query_tags)  # warm up the search to avoid first-query lag
        
        hashes: list[str] = cast(list[str], client.search_files(tags=query_tags, return_hashes=True, file_sort_asc=True, file_sort_type=2))


        click.echo(f"Found {len(hashes)} files (excluding ugoira and video).")
        logging.info(f"Found {len(hashes)} files via tag search")

    elif hashfile:
        if not os.path.isfile(hashfile):
            raise ValueError("hashfile not found!")

        with open(hashfile) as f:
            hashes: list[str] = [line.strip() for line in f if line.strip()]

        logging.info(f"Loaded {len(hashes)} hashes from file")

    else:
        raise ValueError("Provide either --search-tag or --hashfile")

    # -----------------------------
    # Done hash tracking (ONLY for hashfile mode)
    # -----------------------------
    done_hashes: set[str] = set()
    bad_hashes: set[str] = set()

    if not using_tag_search:
        if os.path.exists(done_hashes_file):
            with open(done_hashes_file, "r", encoding="utf-8") as f:
                done_hashes = {line.strip() for line in f if line.strip()}

    if os.path.exists("bad-hashes.txt"):
        with open("bad-hashes.txt", "r", encoding="utf-8") as f:
            bad_hashes = {line.strip() for line in f if line.strip()}

    # -----------------------------
    # Processing Loop
    # -----------------------------
    processed_count = 0
    interrupted = False

    counterh = 1
    totalh = len(hashes)
    @profile(stream=memory_profiler_logg)
    def _show_idh(item) -> str:
        return f"{counterh}/{totalh}"


    try:
        with click.progressbar(hashes, item_show_func=_show_idh) as bar:
            for file_hash in bar:
                counterh += 1

                file_hash = str(file_hash)

                if not file_hash or file_hash in bad_hashes:
                    continue

                if not using_tag_search and file_hash in done_hashes:
                    continue

                click.echo(" processing: " + file_hash)
                logging.info(f"Processing: {file_hash}")

                try:
                    response: Any = get_file_with_retry(client, file_hash)

                except hydrus_api.APIError as e:
                    try:
                        info = e.response.json()
                    except Exception:
                        info = {"status_code": getattr(getattr(e, 'response', None), 'status_code', None), "exception_type": None, "text": getattr(getattr(e, 'response', None), 'text', str(e))}
                    status = info.get("status_code")
                    etype = info.get("exception_type")
                    click.echo(f"Hydrus error {status} ({etype}) on {file_hash}")
                    logging.warning(f"Hydrus error {status} ({etype}) on {file_hash}")

                    if etype == "FileMissingException":
                        click.echo(f"Added to bad-hashes.txt: {file_hash}")
                        bad_hashes.add(file_hash)
                        with open("bad-hashes.txt", "a", encoding="utf-8") as bad_f:
                            bad_f.write(file_hash + "\n")
                        continue
                    else:
                        # real error, not a bad hash
                        raise
                except RuntimeError as e:
                    click.echo(str(e))
                    click.echo("Hydrus seems unreachable — stopping batch.")
                    logging.error(str(e))
                    logging.error("Hydrus seems unreachable — stopping batch.")
                    raise
                image_bytes: BytesIO = BytesIO(response.content)

                try:
                    image: PILImage = Image.open(image_bytes)
                    image = image.convert("RGB").resize((448, 448))
                except (UnidentifiedImageError, OSError):
                    click.echo(f"Skipping unreadable or non-image file: {file_hash}")
                    logging.warning(f"Skipping unreadable or non-image file: {file_hash}")
                    bad_hashes.add(file_hash)
                    with open("bad-hashes.txt", "a", encoding="utf-8") as bad_f:
                        bad_f.write(file_hash + "\n")
                    continue

                ratings: dict[str, float]
                tags: dict[str, float]
                ratings, tags = interrogator.interrogate(image)  # pyright: ignore[reportArgumentType]

                rating: str = "none"
                if modelinfo['ratingsflag']:
                    ratings["none"] = 0.0
                    for key in ratings.keys():
                        if ratings[key] > ratings[rating]:
                            rating = key

                clipped_tags: list[str] = []

                if not ratings_only:
                    for key in tags.keys():
                        if tags[key] > threshold:
                            clipped_tags.append(
                                key.replace("_", " ") if key not in kaomojis else key
                            )
                if not privacy:
                    click.echo("rating: " + rating)
                    click.echo("tags: " + ", ".join(clipped_tags))
                    click.echo()

                if modelinfo['ratingsflag']:
                    clipped_tags.append("rating:" + rating)

                if ratings_only:
                    clipped_tags.append(
                        "ratings only " + modelinfo['modelname'] + " ai generated tags"
                    )
                else:
                    clipped_tags.append(
                        modelinfo['modelname'] + " ai generated tags"
                    )

                client.add_tags(
                    hashes=[file_hash],
                    service_names_to_tags={tag_service: clipped_tags} # pyright: ignore[reportCallIssue]
                )

                processed_count += 1

                # Only write done-hash if using hashfile mode
                if not using_tag_search:
                    done_hashes.add(file_hash)
                    with open(done_hashes_file, "a", encoding="utf-8") as done_f:
                        done_f.write(file_hash + "\n")

                # --- Micro pause: let tag write commit ---
                time.sleep(0.1)
                # --- Macro pause: only every 200 files ---
                if processed_count % 200 == 0:
                    time.sleep(3)
                    logging.info(f"Processed {processed_count} files")

    except KeyboardInterrupt:
        interrupted = True
        click.echo("\n[!] Interrupted by user (Ctrl+C)")
        logging.warning("=== INTERRUPTED BY USER (CTRL+C) ===")

    finally:
        logging.info("=== WD HYDRUS TAGGER FINISHED ===")
        logging.info(f"Total processed: {processed_count}")

        if interrupted:
            logging.info("Run ended due to manual interruption.")
        else:
            logging.info("Run completed normally.")

        logging.shutdown()

        click.echo(f"\nFinished. Total processed: {processed_count}")

        if debug:
            try:
                click.echo("Debug mode: press Enter to exit.")
                input()
            except Exception:
                # If stdin is not available, ignore and continue exiting
                pass

# new frame logic
# =============================================================================================================================================

@profile(stream=memory_profiler_logg)
def process_frames_streaming(
    frame_generator: Iterator[PILImage],
    interrogator,
    similarity_threshold: float,
    threshold: float,
    ratingsflag: bool,
):
    """
    True streaming frame processor with live progress bar.
    No frame list is stored.
    """

    agg_scores: dict[str, float] = {}
    agg_ratings: dict[str, float] = {}

    last_small: Optional[PILImage] = None
    kept_count = 0
    total_count = 0

    with click.progressbar(
        frame_generator,
        label="Streaming & Tagging Frames",
        show_pos=True,
    ) as bar:

        for img in bar:
            total_count += 1

            # similarity check
            small = img.resize((64, 64)).convert("L")

            keep_frame = False
            if last_small is None:
                keep_frame = True
            else:
                diff = ImageChops.difference(small, last_small)
                stat = ImageStat.Stat(diff)
                mean_diff = sum(stat.mean) / len(stat.mean)
                if mean_diff >= similarity_threshold:
                    keep_frame = True

            if not keep_frame:
                img.close()
                continue

            kept_count += 1
            last_small = small

            ratings, tags = interrogator.interrogate(img)

            for t, s in tags.items():
                score = float(s)
                if score > threshold:
                    agg_scores[t] = max(agg_scores.get(t, 0.0), score)

            if ratingsflag:
                for r, s in ratings.items():
                    score = float(s)
                    if score > threshold:
                        agg_ratings[r] = max(agg_ratings.get(r, 0.0), score)

            img.close()

    return agg_scores, agg_ratings, kept_count, total_count

# =============================================================================================================================================
# new evaluate_api_batch_video and video_similarity_calibration

@click.command()
@click.option("--hashfile", help="Text file containing Hydrus hashes")
@click.option("--search-tag", multiple=True,
              help="Hydrus tag(s) to search for (can be used multiple times)")
@click.option("--token", required=True, help="Hydrus API token")
@click.option("--cpu", default=True, help="False to Use GPU instead of CPU")
@click.option("--model", default="wd-eva02-large-tagger-v3",
              help="Tagging model to use")
@click.option("--threshold", default=0.35,
              help="Threshold to drop tags below")
@click.option("--host", default="http://127.0.0.1:45869",
              help="The URL for your Hydrus server ")
@click.option("--tag-service", default="ai tags",
              help="The Hydrus tag service to add tags to")
@click.option("--ratings-only", default=False,
              help="Strip all tags except content rating")
@click.option("--privacy", default=True,
              help="Hide tag output from cli")
@click.option("--debug", is_flag=True, default=False,
              help="Show debug progress for video processing")
@profile(stream=memory_profiler_logg)
def evaluate_api_batch_video(hashfile: Optional[str], search_tag: tuple[str, ...], token: str, cpu: bool,
                             model: str, threshold: float, host: str,
                             tag_service: str, ratings_only: bool, privacy: bool, debug: bool) -> None:
    """Evaluate a batch of multi-frame content (GIF/video) and apply tags with RAM optimization.

    This command is similar to :func:`evaluate_api_batch` but targets
    multi-frame content. For animated GIFs the frames are read via PIL; for
    other video containers the function will attempt to use ``ffmpeg`` (if
    available) to extract one frame per second. Frames are dynamically
    filtered for similarity before interrogation for efficiency.

    The per-frame tag scores are aggregated (averaged) and the resulting tag
    list is applied to the original video file in Hydrus.

    :param hashfile: Optional path to a newline-separated file containing
        Hydrus file hashes to process.
    :param search_tag: One or more Hydrus tags to search for; mutually
        exclusive with ``hashfile``.
    :param token: Hydrus API token for authentication.
    :param cpu: When True, run the interrogator in CPU mode; False to prefer GPU.
    :param model: Local model folder name to load (under ``./model``).
    :param threshold: Minimum tag score threshold to include a tag.
    :param host: URL of the target Hydrus server.
    :param tag_service: Name of the Hydrus tag service to which tags are added.
    :param ratings_only: If True, only the content rating tag is added.
    :param privacy: If True, suppress tag output to the CLI.
    """

    # Setup logging and model like the image batch command
    os.makedirs("logs", exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    logfile = f"logs/{model}_{timestamp}.log"

    logging.basicConfig(
        filename=logfile,
        level=logging.INFO,
        format="%(asctime)s - %(message)s"
    )

    logging.info("=== WD HYDRUS VIDEO TAGGER START ===")
    logging.info(f"Model: {model}")
    logging.info(f"CPU Mode: {cpu}")
    logging.info(f"Tag Service: {tag_service}")

    # Clean up repository-local ffmpeg temporary files from previous runs
    try:
        repo_root = Path(__file__).resolve().parents[1]
        repo_tmp_dir = repo_root / "ffmpeg_temp"
        if repo_tmp_dir.exists():
            for p in repo_tmp_dir.iterdir():
                try:
                    # Delete only folders starting with "deleted_"
                    if p.is_dir() and p.name.startswith("deleted_"):
                        shutil.rmtree(p)
                     # Delete only files matching "frame_*.jpg"
                    elif p.is_file() and p.name.startswith("frame_") and p.suffix == ".jpg":
                        p.unlink()
                except Exception:
                    # ignore individual cleanup errors
                    pass
    except Exception:
        logging.exception("Failed to clean ffmpeg_temp at startup")
        

    if not os.path.isfile('./model/' + model + '/info.json'):
        raise ValueError("info.json not found in model folder!")

    with open('./model/' + model + '/info.json') as json_f:
        modelinfo: dict[str, Any] = json.load(json_f)
        done_hashes_file: str = f"done-hashes-{modelinfo['modelname']}.txt"

    if ratings_only and not modelinfo['ratingsflag']:
        raise ValueError("--ratings-only set, but model does not support ratings!")

    interrogator: interrogate.WaifuDiffusionInterrogator = interrogate.WaifuDiffusionInterrogator(
        modelinfo['modelname'], # the name of the model for display purposes
        modelinfo['modelfile'], # the filename of the model file
        modelinfo['tagsfile'], # the filename of the tags file
        model, # the folder storing the previous two files as well as the info file
		modelinfo['ratingsflag'], # flag indicating whether model identifies content rating
		modelinfo['numberofratings'], # amount of tags to consider for content rating if so
        repo_id=modelinfo['source'], # source of the model, credit where credit is due
    )
    interrogator.load(cpu)

    client: hydrus_api.Client = hydrus_api.Client(token, host)

    # Determine file source (search for video content)
    using_tag_search: bool = False

    if search_tag:
        using_tag_search = True
        logging.info(f"Search Tags: {search_tag}")
        # Include only animated/video types not images
        query_tags: list[str] = list(search_tag) + ["system:filetype is ugoira, video"]


        client.search_files(tags=query_tags)
        hashes: list[str] = cast(list[str], client.search_files(tags=query_tags, return_hashes=True, file_sort_asc=True, file_sort_type=16))
        # sort type 16 is "system:number of frames", which should help with processing efficiency by front-loading shorter videos.

        click.echo(f"Found {len(hashes)} files (animated/video).")
        logging.info(f"Found {len(hashes)} files via tag search")

    elif hashfile:
        if not os.path.isfile(hashfile):
            raise ValueError("hashfile not found!")
        with open(hashfile) as f:
            hashes: list[str] = [line.strip() for line in f if line.strip()]
        logging.info(f"Loaded {len(hashes)} hashes from file")
    else:
        raise ValueError("Provide either --search-tag or --hashfile")

    done_hashes: set[str] = set()
    bad_hashes: set[str] = set()

    if not using_tag_search:
        if os.path.exists(done_hashes_file):
            with open(done_hashes_file, "r", encoding="utf-8") as f:
                done_hashes = {line.strip() for line in f if line.strip()}

    if os.path.exists("bad-hashes.txt"):
        with open("bad-hashes.txt", "r", encoding="utf-8") as f:
            bad_hashes = {line.strip() for line in f if line.strip()}


    processed_count = 0
    interrupted = False

    counterh = 0
    totalh = len(hashes)
    @profile(stream=memory_profiler_logg)
    def _show_idh(item) -> str:
        return f"{counterh}/{totalh} Done"

    try:
        with click.progressbar(hashes, item_show_func=_show_idh) as bar:
            for file_hash in bar:
                counterh += 1

                file_hash = str(file_hash)

                if not file_hash or file_hash in bad_hashes:
                    continue

                if not using_tag_search and file_hash in done_hashes:
                    continue

                click.echo("\n  processing: " + file_hash)
                logging.info(f"Processing: {file_hash}")

                try:
                    response: Any = get_file_with_retry(client, file_hash)

                except hydrus_api.APIError as e:
                    info = e.response.json()
                    status = info.get("status_code")
                    etype = info.get("exception_type")
                    click.echo(f"Hydrus error {status} ({etype}) on {file_hash}")
                    logging.warning(f"Hydrus error {status} ({etype}) on {file_hash}")

                    if etype == "FileMissingException":
                        click.echo(f"Added to bad-hashes.txt: {file_hash}")
                        bad_hashes.add(file_hash)
                        with open("bad-hashes.txt", "a", encoding="utf-8") as bad_f:
                            bad_f.write(file_hash + "\n")
                        continue
                    else:
                        raise
                except RuntimeError as e:
                    click.echo(str(e))
                    click.echo("Hydrus seems unreachable — stopping batch.")
                    logging.error(str(e))
                    logging.error("Hydrus seems unreachable — stopping batch.")
                    raise

                # --- Frame Generators for RAM Efficiency ---
                @profile(stream=memory_profiler_logg)
                def pil_frame_gen(data: bytes):
                    count = 0
                    with Image.open(BytesIO(data)) as container:
                        n = getattr(container, "n_frames", 1)
                        for i in range(n):
                            container.seek(i)
                            count += 1
                            yield container.convert("RGB").resize((448, 448))
                    click.echo(f"\n[pil] Total frames extracted: {count}")
                    logging.info(f"[pil] Total frames extracted: {count} for {file_hash}")

                @profile(stream=memory_profiler_logg)
                def ffmpeg_frame_gen(data: bytes, h: str, tmp_dir: Path):
                    count = 0
                    in_path = tmp_dir / f"vid_{h}"
                    in_path.write_bytes(data)
                    out_pattern = str(tmp_dir / f"frame_{h}_%05d.jpg")
                    
                    repo_root = Path(__file__).resolve().parents[1]
                    bundled_ffmpeg = repo_root / "ffmpeg" / "bin" / ("ffmpeg.exe" if os.name == "nt" else "ffmpeg")
                    ffmpeg_exe = str(bundled_ffmpeg) if bundled_ffmpeg.exists() else "ffmpeg"


                    if debug:
                        subprocess.run(
                            [
                                ffmpeg_exe,
                                "-y",
                                "-i", str(in_path),
                                "-vf", "fps=1",
                                "-q:v", "2",
                                out_pattern
                            ],
                            stdout=subprocess.DEVNULL,
                            stderr=subprocess.DEVNULL,
                            check=False
                        )
                        click.echo()
                        click.echo("ffmpeg done")
                        click.echo()
                    else:
                        subprocess.run([ffmpeg_exe, "-y", "-i", str(in_path), "-vsync", "0", "-q:v", "2", out_pattern],
                                    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False)
                    

                    for p in sorted(tmp_dir.glob(f"frame_{h}_*.jpg")):
                        with Image.open(p) as f_img:
                            count += 1
                            yield f_img.convert("RGB").resize((448, 448))  # Resize for faster processing; adjust as needed
                        p.unlink()
                    if in_path.exists(): in_path.unlink()
                    click.echo(f"\n[ffmpeg] Total frames extracted: {count}")
                    logging.info(f"[ffmpeg] Total frames extracted: {count} for {file_hash}")

                repo_root = Path(__file__).resolve().parents[1]
                repo_tmp_dir = repo_root / "ffmpeg_temp"
                repo_tmp_dir.mkdir(parents=True, exist_ok=True)



                similarity_threshold_ff = 12.0

                try:
                    # Test open once to verify it is PIL-compatible
                    test_img = Image.open(BytesIO(response.content))
                    test_img.close()
                    frame_gen = pil_frame_gen(response.content)
                except UnidentifiedImageError:
                    # Not an image container > use ffmpeg
                    frame_gen = ffmpeg_frame_gen(response.content, file_hash, repo_tmp_dir)

                agg_scores, agg_ratings, kept_frames, total_frames = process_frames_streaming(
                    frame_gen,
                    interrogator,
                    similarity_threshold=similarity_threshold_ff,
                    threshold=threshold,
                    ratingsflag=modelinfo['ratingsflag'],
                )

                click.echo(f"Similarity threshold > {similarity_threshold_ff:.2f}")
                click.echo(f"Kept and tagged {kept_frames} of {total_frames} frames")
                logging.info(f"Similarity threshold > {similarity_threshold_ff:.2f}")
                logging.info(f"Kept and tagged {kept_frames} of {total_frames} frames for {file_hash}")
                click.echo()

                rating_priority = {
                "explicit": 4,
                "questionable": 3,
                "sensitive": 2,
                "general": 1,
                "none": 0
                }


                rating = "none"
                if modelinfo['ratingsflag']:
                    agg_ratings.setdefault("none", 0.0)
                    for r, score in agg_ratings.items():
                        if score > threshold and rating_priority.get(r, 0) > rating_priority.get(rating, 0):
                            rating = r


                clipped_tags = [k.replace("_", " ") if k not in kaomojis else k for k, v in agg_scores.items() if v > threshold]

                if not privacy:
                    click.echo("rating: " + rating)
                    click.echo("tags: " + ", ".join(clipped_tags))
                    click.echo()

                if modelinfo['ratingsflag']:
                    clipped_tags.append("rating:" + rating)

                
                clipped_tags.append(f"{modelinfo['modelname']} ai generated tags")


                client.add_tags(
                    hashes=[file_hash], 
                    service_names_to_tags={tag_service: clipped_tags})

                processed_count += 1
                gc.collect()


                if not using_tag_search:
                    done_hashes.add(file_hash)
                    with open(done_hashes_file, "a", encoding="utf-8") as done_f:
                        done_f.write(file_hash + "\n")

                time.sleep(0.1)

                if processed_count % 10 == 0:
                    time.sleep(3)
                    logging.info(f"Processed {processed_count} files")

    except KeyboardInterrupt:
        interrupted = True
        click.echo("\n[!] Interrupted by user (Ctrl+C)")
        logging.warning("=== INTERRUPTED BY USER (CTRL+C) ===")

    finally:
        logging.info("=== WD HYDRUS VIDEO TAGGER FINISHED ===")
        logging.info(f"Total processed: {processed_count}")

        if interrupted:
            logging.info("Run ended due to manual interruption.")
        else:
            logging.info("Run completed normally.")

        logging.shutdown()

        click.echo(f"\nFinished. Total processed: {processed_count}")

        if debug:
            try:
                click.echo("Debug mode: press Enter to exit.")
                input()
            except Exception:
                # If stdin is not available, ignore and continue exiting
                pass


# curently broken x2
@click.command(name="video_similarity_calibration")
@click.option("--file-hash", help="Hydrus file hash to fetch (mutually exclusive with --local-file)")
@click.option("--local-file", help="Path to a local video file (mutually exclusive with --file-hash)")
@click.option("--token", help="Hydrus API token (required if --file-hash used)")
@click.option("--host", default="http://127.0.0.1:45869", help="Hydrus host (used with --file-hash)")
@click.option("--similarity", default="10.0,9.0,8.0,7.0,6.0,5.0,4.0,3.0,2.0,1.0", help="Comma-separated similarity thresholds to test, e.g. '10.0,9.0,8.0'")
@click.option("--max-frames", default=0, type=int, help="Maximum frames to keep per threshold (0 = unlimited)")
@click.option("--debug", is_flag=True, default=False, help="Show debug output and keep extracted frames")
@profile(stream=memory_profiler_logg)
def video_similarity_calibration(
    file_hash: Optional[str],
    local_file: Optional[str],
    token: Optional[str],
    host: str,
    similarity: str,
    max_frames: int,
    debug: bool
) -> None:
    """Calibration helper: determine optimal similarity thresholds while monitoring memory usage.

    Fetches a video (Hydrus by hash or local file), extracts frames, runs
    _select_frames_streaming for each similarity threshold, and logs results.
    Outputs a summary file in `ffmpeg_temp` with frame selection counts.

    This never sends tags back to Hydrus.
    """


    content_bytes: bytes
    label: str

    # --- Fetch content ---
    if file_hash:
        click.echo(f"[INFO] Fetching video from Hydrus with hash {file_hash}")
        logging.info(f"Fetching video from Hydrus: {file_hash}")
        client = hydrus_api.Client(token, host)
        response = get_file_with_retry(client, file_hash)
        content_bytes = response.content
        label = file_hash
        click.echo(f"[INFO] Retrieved video of size {len(content_bytes)} bytes")
    elif local_file:
        p = Path(local_file)
        click.echo(f"[INFO] Reading local file {local_file}")
        logging.info(f"Reading local file: {local_file}")
        content_bytes = p.read_bytes()
        label = p.stem
        click.echo(f"[INFO] Local file size: {len(content_bytes)} bytes")
    else:
        raise ValueError("Provide --file-hash or --local-file")

    # --- Setup logging ---
    os.makedirs("logs", exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    logfile = f"logs/vsc_{timestamp}_{label}.log"

    logging.basicConfig(
        filename=logfile,
        level=logging.INFO if not debug else logging.DEBUG,
        format="%(asctime)s - %(levelname)s - %(message)s"
    )
    click.echo(f"[INFO] Logging to {logfile}")

    # --- Parse similarity thresholds ---
    similarity_list = [float(s.strip()) for s in similarity.split(",") if s.strip()]
    click.echo(f"[INFO] Similarity thresholds to test: {similarity_list}")
    logging.info(f"Similarity thresholds: {similarity_list}")

    # --- Prepare repository temp folder ---
    repo_root = Path(__file__).resolve().parents[1]
    repo_tmp_dir = repo_root / "ffmpeg_temp"
    repo_tmp_dir.mkdir(parents=True, exist_ok=True)
    click.echo(f"[INFO] Temporary output directory: {repo_tmp_dir}")

    # --- Frame generator ---
    @profile(stream=memory_profiler_logg)
    def pil_gen(data: bytes):
        """Yield frames from video or animated image, resized to 320x320."""
        click.echo(f"[INFO] Starting frame extraction...")

        # Try animated image first (GIF/WebP/etc.)
        try:
            img = Image.open(BytesIO(data))
            if getattr(img, "is_animated", False) or getattr(img, "n_frames", 1) > 1:
                click.echo("[INFO] Detected animated image. Extracting frames...")
                for i in range(getattr(img, "n_frames", 1)):
                    img.seek(i)
                    yield img.convert("RGB")
                img.close()
                click.echo("[INFO] Completed frame extraction from animated image.")
                return
            img.close()
        except Exception as e:
            click.echo(f"[DEBUG] Not an animated image: {e}")

        # Assume video, use ffmpeg streaming
        bundled_ffmpeg = repo_root / "ffmpeg" / "bin" / ("ffmpeg.exe" if os.name == 'nt' else "ffmpeg")
        ffmpeg_cmd = str(bundled_ffmpeg) if bundled_ffmpeg.exists() else "ffmpeg"
        click.echo(f"[INFO] Using ffmpeg command: {ffmpeg_cmd}")

        width = 320
        height = 320
        frame_size = width * height * 3
        cmd = [
            ffmpeg_cmd,
            "-i", "pipe:0",
            "-vf", f"scale={width}:{height}",
            "-f", "image2pipe",
            "-pix_fmt", "rgb24",
            "-vcodec", "rawvideo",
            "-"
        ]
        click.echo(f"[DEBUG] ffmpeg command: {' '.join(cmd)}")

        proc = subprocess.Popen(
            cmd,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL
        )

        try:
            proc.stdin.write(data) # pyright: ignore[reportOptionalMemberAccess]
            proc.stdin.close() # pyright: ignore[reportOptionalMemberAccess]
            frame_count = 0

            while True:
                raw = proc.stdout.read(frame_size) # pyright: ignore[reportOptionalMemberAccess]
                if len(raw) != frame_size:
                    break
                frame = Image.frombytes("RGB", (width, height), raw)
                frame_count += 1
                yield frame

            click.echo(f"[INFO] Extracted {frame_count} frames from video stream")
        finally:
            proc.stdout.close() # pyright: ignore[reportOptionalMemberAccess]
            proc.wait()
            click.echo("[INFO] ffmpeg process finished")

    # --- Run calibration ---
    click.echo(f"[INFO] Starting calibration for {label}")
    for thr in similarity_list:
        click.echo(f"[INFO] Processing similarity threshold: {thr}")
        selected = _select_frames_streaming( # pyright: ignore[reportUndefinedVariable]
            pil_gen(content_bytes),
            similarity_threshold=thr,
            max_frames=max_frames
        )
        click.echo(f"[RESULT] Threshold {thr}: selected {len(selected)} frames")
        logging.info(f"Threshold {thr}: selected {len(selected)} frames")

        # Log summary
        try:
            summary_file = repo_tmp_dir / f"summary_{label}.txt"
            with open(summary_file, "a", encoding="utf-8") as sf:
                sf.write(f"Threshold {thr}: selected {len(selected)} frames\n")
            click.echo(f"[INFO] Written summary for threshold {thr}")
        except Exception as e:
            click.echo(f"[WARNING] Could not write summary: {e}")

        # Clean up frames
        for f in selected: 
            f.close()

        if len(selected) <= 1:
            click.echo("[INFO] Early exit: fewer than 2 frames selected")
            break

    click.echo(f"[INFO] Calibration artifacts written to: {repo_tmp_dir}")
    logging.info("Calibration complete.")


# =============================================================================================================================================
# legacy versions of select_frames, batch_video and similarity_calibration functions 
# are kept below for reference, testing and comparison purposes, 
# but should not be used in the main command flow. 

# the new streaming versions are designed to be more memory efficient 
# and should be used in the main video batch command to avoid memory issues with long videos.


# f me i hate this code so much
# (╯°□°)╯︵ ┻━┻


# float=
# similarity threshold for frame selection. Adjust to make filtering more or less aggressive.
# the default value of 12.0 was chosen based on some testing using using legacy_video_similarity_calibration,
# to avrage around the point where a speed gain would decrease and tag quality would start to noticeably degrade for some videos.
# but the optimal threshold may vary depending on the specific videos being processed and the desired balance between tag accuracy and processing efficiency.
# Depending on the content and frame rate of the videos being processed, users may want to adjust this threshold up or down.
# A lower threshold will keep more frames (including those with minor differences), 
# while a higher threshold will be more selective and keep only frames that are more visually distinct from the last-kept frame.

# max_frames=
# 0 means no limit; set to a positive integer to keep only the first N sufficiently different frames.
@profile(stream=memory_profiler_logg)
def _Legacy_select_frames_from_images(images: list[PILImage], similarity_threshold: float = 12.0, max_frames: int = 0) -> list[PILImage]:
    """Select a subset of frames from a sequence by simple similarity filtering.

    The function performs a lightweight pairwise comparison using resized
    grayscale frame differences and only keeps a frame if it is sufficiently
    different from the last-kept frame. This reduces redundant frames and
    controls processing cost.

    :param images: Sequence of PIL images (RGB) to filter.
    :param similarity_threshold: Mean-difference threshold to decide if two
        frames are different enough to keep.
    :param max_frames: Maximum number of frames to keep. Use 0 for no limit.
    :returns: A list of selected PIL images.
    """
    selected: list[PILImage] = []
    last_small = None
    for img in images:
        small = img.copy().resize((64, 64)).convert("L")
        if last_small is None:
            selected.append(img)
            last_small = small
        else:
            diff = ImageChops.difference(small, last_small)
            stat = ImageStat.Stat(diff)
            mean_diff = sum(stat.mean) / len(stat.mean)
            if mean_diff >= similarity_threshold:
                selected.append(img)
                last_small = small
        # If max_frames is > 0 enforce the limit; if 0 treat as unlimited
        if max_frames > 0 and len(selected) >= max_frames:
            break
    return selected


@click.command()
@click.option("--hashfile", help="Text file containing Hydrus hashes")
@click.option("--search-tag", multiple=True,
              help="Hydrus tag(s) to search for (can be used multiple times)")
@click.option("--token", required=True, help="Hydrus API token")
@click.option("--cpu", default=True, help="False to Use GPU instead of CPU")
@click.option("--model", default="wd-eva02-large-tagger-v3",
              help="Tagging model to use")
@click.option("--threshold", default=0.35,
              help="Threshold to drop tags below")
@click.option("--host", default="http://127.0.0.1:45869",
              help="The URL for your Hydrus server ")
@click.option("--tag-service", default="ai tags",
              help="The Hydrus tag service to add tags to")
@click.option("--ratings-only", default=False,
              help="Strip all tags except content rating")
@click.option("--privacy", default=True,
              help="Hide tag output from cli")
@click.option("--debug", is_flag=True, default=False,
              help="Show debug progress for video processing")
@profile(stream=memory_profiler_logg)
def legacy_evaluate_api_batch_video(hashfile: Optional[str], search_tag: tuple[str, ...], token: str, cpu: bool,
                             model: str, threshold: float, host: str,
                             tag_service: str, ratings_only: bool, privacy: bool, debug: bool) -> None:
    """Evaluate a batch of multi-frame content (GIF/video) and apply tags.

    This command is similar to :func:`evaluate_api_batch` but targets
    multi-frame content. For animated GIFs the frames are read via PIL; for
    other video containers the function will attempt to use ``ffmpeg`` (if
    available) to extract one frame per second. Frames are dynamically
    filtered for similarity before interrogation for efficiency.

    The per-frame tag scores are aggregated (averaged) and the resulting tag
    list is applied to the original video file in Hydrus.

    :param hashfile: Optional path to a newline-separated file containing
        Hydrus file hashes to process.
    :param search_tag: One or more Hydrus tags to search for; mutually
        exclusive with ``hashfile``.
    :param token: Hydrus API token for authentication.
    :param cpu: When True, run the interrogator in CPU mode; False to prefer GPU.
    :param model: Local model folder name to load (under ``./model``).
    :param threshold: Minimum tag score threshold to include a tag.
    :param host: URL of the target Hydrus server.
    :param tag_service: Name of the Hydrus tag service to which tags are added.
    :param ratings_only: If True, only the content rating tag is added.
    :param privacy: If True, suppress tag output to the CLI.
    """

    # Setup logging and model like the image batch command
    os.makedirs("logs", exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    logfile = f"logs/{model}_{timestamp}.log"

    logging.basicConfig(
        filename=logfile,
        level=logging.INFO,
        format="%(asctime)s - %(message)s"
    )

    logging.info("=== WD HYDRUS VIDEO TAGGER START ===")
    logging.info(f"Model: {model}")
    logging.info(f"CPU Mode: {cpu}")
    logging.info(f"Tag Service: {tag_service}")
    # Clean up repository-local ffmpeg temporary files from previous runs
    try:
        repo_root = Path(__file__).resolve().parents[1]
        repo_tmp_dir = repo_root / "ffmpeg_temp"
        if repo_tmp_dir.exists():
            for p in repo_tmp_dir.iterdir():
                try:
                    # Delete only folders starting with "deleted_"
                    if p.is_dir() and p.name.startswith("deleted_"):
                        shutil.rmtree(p)
                     # Delete only files matching "frame_*.jpg"
                    elif p.is_file() and p.name.startswith("frame_") and p.suffix == ".jpg":
                        p.unlink()
                except Exception:
                    # ignore individual cleanup errors
                    pass
    except Exception:
        logging.exception("Failed to clean ffmpeg_temp at startup")

    if not os.path.isfile('./model/' + model + '/info.json'):
        raise ValueError("info.json not found in model folder!")

    with open('./model/' + model + '/info.json') as json_f:
        modelinfo: dict[str, Any] = json.load(json_f)
        done_hashes_file: str = f"done-hashes-{modelinfo['modelname']}.txt"

    if ratings_only and not modelinfo['ratingsflag']:
        raise ValueError("--ratings-only set, but model does not support ratings!")

    interrogator: interrogate.WaifuDiffusionInterrogator = interrogate.WaifuDiffusionInterrogator(
        modelinfo['modelname'],
        modelinfo['modelfile'],
        modelinfo['tagsfile'],
        model,
        modelinfo['ratingsflag'],
        modelinfo['numberofratings'],
        repo_id=modelinfo['source'],
    )
    interrogator.load(cpu)

    client: hydrus_api.Client = hydrus_api.Client(token, host)

    # Determine file source (search for video content)
    using_tag_search: bool = False

    if search_tag:
        using_tag_search = True
        logging.info(f"Search Tags: {search_tag}")
        # Include only animated/video types
        query_tags: list[str] = list(search_tag) + ["system:filetype is ugoira, video", "system:number of frames < 2,500", "system:filesize < 200MB"]
        # system:number of frames < 2,500
        # system:filesize < 200MB
        # lose safeguards against long/big videos that would cause memory issues in the frame selection code.
        # this is a bit of a hack as ther seems to be a memory leak 
        # or just bad code in my _Legacy_select_frames_from_images function that causes it to consume more and more memory the more frames it processes.
        # this is a crude way to skip those while still allowing many other videos to be processed. 
        # Ideally I would fix the underlying issue in the frame selection code, 
        # but in the meantime this is a practical workaround to avoid crashing or freezing.

        client.search_files(tags=query_tags)
        hashes: list[str] = cast(list[str], client.search_files(tags=query_tags, return_hashes=True, file_sort_asc=True, file_sort_type=16))
        # sort type 16 is "system:number of frames", which should help with processing efficiency by front-loading shorter videos that are less likely to hit memory issues

        click.echo(f"Found {len(hashes)} files (animated/video).")
        logging.info(f"Found {len(hashes)} files via tag search")

    elif hashfile:
        if not os.path.isfile(hashfile):
            raise ValueError("hashfile not found!")

        with open(hashfile) as f:
            hashes: list[str] = [line.strip() for line in f if line.strip()]

        logging.info(f"Loaded {len(hashes)} hashes from file")

    else:
        raise ValueError("Provide either --search-tag or --hashfile")

    done_hashes: set[str] = set()
    bad_hashes: set[str] = set()

    if not using_tag_search:
        if os.path.exists(done_hashes_file):
            with open(done_hashes_file, "r", encoding="utf-8") as f:
                done_hashes = {line.strip() for line in f if line.strip()}

    if os.path.exists("bad-hashes.txt"):
        with open("bad-hashes.txt", "r", encoding="utf-8") as f:
            bad_hashes = {line.strip() for line in f if line.strip()}

    processed_count = 0
    interrupted = False

    # gpt speacial: 
    # I added a custom progress bar item_show_func to display the current index and total count of hashes being processed,
    # since video processing can take significantly longer than single images and it's helpful to have a sense of progress through the batch. 
    # The counterh generator is used to keep track of the current index in a way that works with the progress bar's iteration. 
    # This should provide more informative progress feedback during long video batch runs.
    counterh = count(1)
    totalh = len(hashes)
    @profile(stream=memory_profiler_logg)
    def _show_idh(_):
        return f"{next(counterh)}/{totalh}"

    try:
        with click.progressbar(hashes, length=totalh, item_show_func=_show_idh) as bar:
            for file_hash in bar:
                file_hash = str(file_hash)

                if not file_hash or file_hash in bad_hashes:
                    continue

                if not using_tag_search and file_hash in done_hashes:
                    continue

                click.echo(" processing: " + file_hash)
                logging.info(f"Processing: {file_hash}")

                try:
                    response: Any = get_file_with_retry(client, file_hash)

                except hydrus_api.APIError as e:
                    info = e.response.json()
                    status = info.get("status_code")
                    etype = info.get("exception_type")
                    click.echo(f"Hydrus error {status} ({etype}) on {file_hash}")
                    logging.warning(f"Hydrus error {status} ({etype}) on {file_hash}")

                    if etype == "FileMissingException":
                        click.echo(f"Added to bad-hashes.txt: {file_hash}")
                        bad_hashes.add(file_hash)
                        with open("bad-hashes.txt", "a", encoding="utf-8") as bad_f:
                            bad_f.write(file_hash + "\n")
                        continue
                    else:
                        raise
                except RuntimeError as e:
                    click.echo(str(e))
                    click.echo("Hydrus seems unreachable — stopping batch.")
                    logging.error(str(e))
                    logging.error("Hydrus seems unreachable — stopping batch.")
                    raise

                images: list[PILImage] = []

                # Try to open as an animated image first (GIF, APNG via PIL)
                try:
                    image_bytes = BytesIO(response.content)
                    img = Image.open(image_bytes)
                    if getattr(img, "is_animated", False) or getattr(img, "n_frames", 1) > 1:
                        for i in range(getattr(img, "n_frames", 1)):
                            img.seek(i)
                            frame = img.convert("RGB").copy()
                            images.append(frame)
                        click.echo(f"  found {len(images)} frames via PIL animation")
                        logging.info(f"Found {len(images)} frames via PIL animation")
                    else:
                        img.close()
                except Exception:
                    images = []

                # If not an animated image, attempt ffmpeg frame extraction
                tmpdir = None
                if not images:
                    # prefer using a repo-local temporary directory instead of
                    # the system/AppData temp folder so extracted frames stay
                    # inside the repository
                    repo_root = Path(__file__).resolve().parents[1]
                    repo_tmp_dir = repo_root / "ffmpeg_temp"
                    repo_tmp_dir.mkdir(parents=True, exist_ok=True)
                    in_path = repo_tmp_dir / f"input_{file_hash}"
                    with open(in_path, "wb") as f:
                        f.write(response.content)

                    out_pattern = str(repo_tmp_dir / f"frame_{file_hash}_%05d.jpg")
                    # Prefer bundled ffmpeg in the repository under ./ffmpeg/bin,
                    # otherwise fall back to system `ffmpeg` on PATH.
                    repo_root = Path(__file__).resolve().parents[1]
                    bundled_ffmpeg = repo_root / "ffmpeg" / "bin" / ("ffmpeg.exe" if os.name == "nt" else "ffmpeg")
                    if bundled_ffmpeg.exists():
                        ffmpeg_cmd = str(bundled_ffmpeg)
                        #logging.info(f"Using bundled ffmpeg: {ffmpeg_cmd}")
                    else:
                        ffmpeg_cmd = "ffmpeg"
                        #logging.info("Using system ffmpeg (no bundled ffmpeg found)")

                    # extract all frames; ffmpeg may be absent — ignore errors
                    # use -vsync 0 to avoid duplicate/drop frames, output as images
                    cmd = [ffmpeg_cmd, "-y", "-i", str(in_path), "-fps_mode", "passthrough", "-q:v", "2", out_pattern]
                    try:
                        if debug:
                            click.echo("  extracting frames with ffmpeg...")
                            subprocess.run(cmd, check=False)
                        else:
                            click.echo("  extracting frames with ffmpeg...")
                            subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False)
                        frames = sorted(repo_tmp_dir.glob(f"frame_{file_hash}_*.jpg"))
                        for p in frames:
                            try:
                                fimg = Image.open(p).convert("RGB")
                                images.append(fimg)
                            except Exception:
                                continue
                        click.echo(f"  extracted {len(frames)} frames via ffmpeg")
                        logging.info(f"Extracted {len(frames)} frames via ffmpeg")
                    except FileNotFoundError:
                        # ffmpeg not found; treat as unreadable video
                        images = []

                if not images:
                    click.echo(f"Skipping unreadable or unsupported multi-frame file: {file_hash}")
                    logging.warning(f"Skipping unreadable or unsupported multi-frame file: {file_hash}")
                    bad_hashes.add(file_hash)
                    with open("bad-hashes.txt", "a", encoding="utf-8") as bad_f:
                        bad_f.write(file_hash + "\n")
                    # remove any ffmpeg files produced for this hash, including
                    # any previously-moved unused frames in deleted_{hash}
                    try:
                        for p in repo_tmp_dir.glob(f"frame_{file_hash}_*.jpg"): # pyright: ignore[reportOptionalMemberAccess, reportPossiblyUnboundVariable]
                            try:
                                p.unlink()
                            except Exception:
                                pass
                        in_file = repo_tmp_dir / f"input_{file_hash}" # pyright: ignore[reportPossiblyUnboundVariable, reportOperatorIssue]
                        if in_file.exists():
                            try:
                                in_file.unlink()
                            except Exception:
                                pass
                        deleted_dir = repo_tmp_dir / f"deleted_{file_hash}" # pyright: ignore[reportOperatorIssue, reportPossiblyUnboundVariable]
                        if deleted_dir.exists():
                            try:
                                shutil.rmtree(deleted_dir)
                            except Exception:
                                pass
                    except Exception:
                        pass
                    continue

                selected = _Legacy_select_frames_from_images(images)
                click.echo(f"  selected {len(selected)} frames after similarity filtering")
                logging.info(f"Selected {len(selected)} frames after similarity filtering")

                # If frames were extracted to the repository temp dir, remove
                # any on-disk frame images that were not selected so the temp
                # folder doesn't accumulate unused files.
                try:
                    repo_tmp_dir  # pyright: ignore[reportPossiblyUnboundVariable, reportUnusedExpression] # check if the variable exists in this scope
                except NameError:
                    repo_tmp_dir = None

                if repo_tmp_dir is not None and repo_tmp_dir.exists(): # type: ignore
                    frames_on_disk = sorted(repo_tmp_dir.glob(f"frame_{file_hash}_*.jpg")) # pyright: ignore[reportPossiblyUnboundVariable]
                    if frames_on_disk:
                        if debug:
                            # In debug mode, move unused extracted frames to a
                            # per-hash "deleted" subfolder so the user can inspect
                            # them separately.
                            deleted_dir = repo_tmp_dir / f"deleted_{file_hash}" # pyright: ignore[reportPossiblyUnboundVariable, reportOperatorIssue]
                            try:
                                deleted_dir.mkdir(parents=True, exist_ok=True)
                            except Exception:
                                deleted_dir = None

                            # Determine which indices were kept by identity comparison
                            used_indices = {i for i, img in enumerate(images) if img in selected}
                            for idx, p in enumerate(frames_on_disk):
                                if idx not in used_indices:
                                    if deleted_dir is not None:
                                        try:
                                            p.rename(deleted_dir / p.name)
                                        except Exception:
                                            try:
                                                p.unlink()
                                            except Exception:
                                                pass
                                    else:
                                        try:
                                            p.unlink()
                                        except Exception:
                                            pass
                        else:
                            # Not in debug mode: keep all extracted frames in the
                            # temp folder until the per-hash final cleanup runs.
                            pass

                # If debug flag set, pause after similarity filtering so user can
                # inspect selected frames before tagging continues.
                if debug:
                    try:
                        click.echo("Debug: press Enter to continue after similarity filtering.")
                        input()
                    except Exception:
                        pass

                # Aggregate tags over selected frames
                agg_scores: dict[str, float] = {}
                agg_ratings: dict[str, float] = {}
                frames_processed = 0
                total_frames = len(selected)
                click.echo(f"  starting tagging of {total_frames} frames")
                logging.info(f"Starting tagging of {total_frames} frames")

                @profile(stream=memory_profiler_logg)
                def _show_idx(item) -> str:
                    # item is a (idx, frame) tuple when using enumerate
                    try:
                        idx = item[0]
                        return f"{idx+1}/{total_frames}"
                    except Exception:
                        return ""

                enumerated = list(enumerate(selected))
                with click.progressbar(enumerated, label="Tagging frames", length=total_frames, item_show_func=_show_idx) as pbar:
                    for idx, frame in pbar:
                        ratings, tags = interrogator.interrogate(frame)
                        for t, s in tags.items():
                            agg_scores[t] = agg_scores.get(t, 0.0) + float(s)
                        for r, s in ratings.items():
                            agg_ratings[r] = agg_ratings.get(r, 0.0) + float(s)
                        frames_processed += 1

                if frames_processed == 0:
                    click.echo(f"No usable frames for {file_hash}")
                    logging.warning(f"No usable frames for {file_hash}")
                    # remove any ffmpeg files produced for this hash, including
                    # any previously-moved unused frames in deleted_{hash}
                    try:
                        for p in repo_tmp_dir.glob(f"frame_{file_hash}_*.jpg"): # pyright: ignore[reportOptionalMemberAccess, reportPossiblyUnboundVariable]
                            try:
                                p.unlink()
                            except Exception:
                                pass
                        in_file = repo_tmp_dir / f"input_{file_hash}" # pyright: ignore[reportPossiblyUnboundVariable, reportOperatorIssue]
                        if in_file.exists():
                            try:
                                in_file.unlink()
                            except Exception:
                                pass
                        deleted_dir = repo_tmp_dir / f"deleted_{file_hash}" # pyright: ignore[reportPossiblyUnboundVariable, reportOperatorIssue]
                        if deleted_dir.exists():
                            try:
                                shutil.rmtree(deleted_dir)
                            except Exception:
                                pass
                    except Exception:
                        pass
                    continue

                # Ensure all selected frames were actually processed before sending tags
                if frames_processed != total_frames:
                    click.echo(f"Incomplete frame processing ({frames_processed}/{total_frames}) for {file_hash} — skipping tag write")
                    logging.warning(f"Incomplete frame processing ({frames_processed}/{total_frames}) for {file_hash} — skipping tag write")
                    # cleanup ffmpeg files for this hash, including any moved
                    # unused frames stored in deleted_{hash}
                    try:
                        for p in repo_tmp_dir.glob(f"frame_{file_hash}_*.jpg"): # pyright: ignore[reportOptionalMemberAccess, reportPossiblyUnboundVariable]
                            try:
                                p.unlink()
                            except Exception:
                                pass
                        in_file = repo_tmp_dir / f"input_{file_hash}" # pyright: ignore[reportPossiblyUnboundVariable, reportOperatorIssue]
                        if in_file.exists():
                            try:
                                in_file.unlink()
                            except Exception:
                                pass
                        deleted_dir = repo_tmp_dir / f"deleted_{file_hash}" # pyright: ignore[reportPossiblyUnboundVariable, reportOperatorIssue]
                        if deleted_dir.exists():
                            try:
                                shutil.rmtree(deleted_dir)
                            except Exception:
                                pass
                    except Exception:
                        pass
                    continue

                click.echo(f"  processed {frames_processed} frames for {file_hash}")
                logging.info(f"Processed {frames_processed} frames for {file_hash}")

                # average scores across frames
                for k in list(agg_scores.keys()):
                    agg_scores[k] /= frames_processed
                for k in list(agg_ratings.keys()):
                    agg_ratings[k] /= frames_processed

                # Pick rating as the highest-averaged rating key
                rating = "none"
                if modelinfo['ratingsflag']:
                    agg_ratings.setdefault("none", 0.0)
                    for key in agg_ratings.keys():
                        if agg_ratings[key] > agg_ratings[rating]:
                            rating = key

                clipped_tags: list[str] = []
                if not ratings_only:
                    for key, score in agg_scores.items():
                        if score > threshold:
                            clipped_tags.append(key.replace("_", " ") if key not in kaomojis else key)

                if not privacy:
                    click.echo("rating: " + rating)
                    click.echo("tags: " + ", ".join(clipped_tags))
                    click.echo()

                if modelinfo['ratingsflag']:
                    clipped_tags.append("rating:" + rating)

                if ratings_only:
                    clipped_tags.append("ratings only " + modelinfo['modelname'] + " ai generated tags")
                else:
                    clipped_tags.append(modelinfo['modelname'] + " ai generated tags")

                client.add_tags(
                    hashes=[file_hash],
                    service_names_to_tags={tag_service: clipped_tags} # pyright: ignore[reportCallIssue]
                )

                processed_count += 1

                if not using_tag_search:
                    done_hashes.add(file_hash)
                    with open(done_hashes_file, "a", encoding="utf-8") as done_f:
                        done_f.write(file_hash + "\n")

                time.sleep(0.1)

                # cleanup ffmpeg files created for this hash, including any moved
                # unused frames stored in deleted_{hash}
                try:
                    for p in repo_tmp_dir.glob(f"frame_{file_hash}_*.jpg"): # pyright: ignore[reportOptionalMemberAccess, reportPossiblyUnboundVariable]
                        try:
                            p.unlink()
                        except Exception:
                            pass
                    in_file = repo_tmp_dir / f"input_{file_hash}" # pyright: ignore[reportPossiblyUnboundVariable, reportOperatorIssue]
                    if in_file.exists():
                        try:
                            in_file.unlink()
                        except Exception:
                            pass
                    deleted_dir = repo_tmp_dir / f"deleted_{file_hash}" # pyright: ignore[reportPossiblyUnboundVariable, reportOperatorIssue]
                    if deleted_dir.exists():
                        try:
                            shutil.rmtree(deleted_dir)
                        except Exception:
                            pass
                except Exception:
                    pass

                if processed_count % 200 == 0:
                    time.sleep(3)
                    logging.info(f"Processed {processed_count} files")

    except KeyboardInterrupt:
        interrupted = True
        click.echo("\n[!] Interrupted by user (Ctrl+C)")
        logging.warning("=== INTERRUPTED BY USER (CTRL+C) ===")

    finally:
        logging.info("=== WD HYDRUS VIDEO TAGGER FINISHED ===")
        logging.info(f"Total processed: {processed_count}")

        if interrupted:
            logging.info("Run ended due to manual interruption.")
        else:
            logging.info("Run completed normally.")

        logging.shutdown()

        click.echo(f"\nFinished. Total processed: {processed_count}")

        if debug:
            try:
                click.echo("Debug mode: press Enter to exit.")
                input()
            except Exception:
                # If stdin is not available, ignore and continue exiting
                pass


@click.command(name="legacy_video_similarity_calibration")
@click.option("--file-hash", help="Hydrus file hash to fetch (mutually exclusive with --local-file)")
@click.option("--local-file", help="Path to a local video file (mutually exclusive with --file-hash)")
@click.option("--token", help="Hydrus API token (required if --file-hash used)")
@click.option("--host", default="http://127.0.0.1:45869", help="Hydrus host (used with --file-hash)")
@click.option("--similarity", default="10.0,9.0,8.0,7.0,6.0,5.0,4.0,3.0,2.0,1.0", help="Comma-separated similarity thresholds to test, e.g. '10.0,9.0,8.0'")
@click.option("--max-frames", default=0, type=int, help="Maximum frames to keep per threshold (0 = unlimited)")
@click.option("--debug", is_flag=True, default=False, help="Show debug output and keep extracted frames")
@profile(stream=memory_profiler_logg)
def legacy_video_similarity_calibration(file_hash: Optional[str], local_file: Optional[str], token: Optional[str], host: str, similarity: str, max_frames: int, debug: bool) -> None:
    """Calibration helper: extract frames and test similarity thresholds.

    Fetches a single video either from Hydrus (by hash) or from a local file,
    extracts frames (PIL or ffmpeg), runs `_Legacy_select_frames_from_images` for
    each supplied `--similarity` value and writes the results to the CLI and a summary text file in the repository. 
    This allows users to calibrate the similarity threshold for frame selection by seeing how many frames are kept at different thresholds for a given video. 
    The summary text file is written to the repository's `ffmpeg_temp` folder with a name like `summary_{hash}.txt` or `summary_{localfilename}.txt`.

    IMPORTANT: This command never sends tags back to Hydrus.
    """
    if not file_hash and not local_file:
        raise ValueError("Provide either --file-hash or --local-file")
    if file_hash and not token:
        raise ValueError("--token is required when using --file-hash")

    # Obtain bytes for the input file
    content_bytes: bytes
    label = None
    if file_hash:
        client = hydrus_api.Client(token, host)
        try:
            response = get_file_with_retry(client, file_hash)
        except Exception as e:
            click.echo(f"Failed to fetch file from Hydrus: {e}")
            return
        content_bytes = response.content
        label = file_hash
    else:
        p = Path(local_file) # pyright: ignore[reportArgumentType]
        if not p.exists():
            raise ValueError("Local file not found")
        with open(p, "rb") as f:
            content_bytes = f.read()
        label = p.stem


    # Setup logging and model like the image batch command
    os.makedirs("logs", exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    logfile = f"logs/vsc_{timestamp}_{label}.log"

    logging.basicConfig(
        filename=logfile,
        level=logging.INFO,
        format="%(asctime)s - %(message)s"
    )



    images: list[PILImage] = []
    extracted_frames_count: Optional[int] = None

    # Parse similarity thresholds: accept comma-separated string like "10.0,9.0,8.0"
    try:
        if isinstance(similarity, str):
            similarity_list: list[float] = [float(s.strip()) for s in similarity.split(",") if s.strip()]
        else:
            similarity_list = list(similarity)
    except Exception:
        click.echo("Invalid --similarity format; expected comma-separated floats")
        return

    # Try PIL animated image first
    try:
        img = Image.open(BytesIO(content_bytes))
        if getattr(img, "is_animated", False) or getattr(img, "n_frames", 1) > 1:
            for i in range(getattr(img, "n_frames", 1)):
                img.seek(i)
                frame = img.convert("RGB").copy()
                images.append(frame)
            click.echo(f"Found {len(images)} frames via PIL animation")
        else:
            img.close()
    except Exception:
        images = []

    # If not animated via PIL, try ffmpeg extraction into repo-local tmp
    repo_root = Path(__file__).resolve().parents[1]
    repo_tmp_dir = repo_root / "ffmpeg_temp"
    repo_tmp_dir.mkdir(parents=True, exist_ok=True)

    if not images:
        in_path = repo_tmp_dir / f"input_{label}"
        with open(in_path, "wb") as f:
            f.write(content_bytes)

        out_pattern = str(repo_tmp_dir / f"frame_{label}_%05d.jpg")
        bundled_ffmpeg = repo_root / "ffmpeg" / "bin" / ("ffmpeg.exe" if os.name == 'nt' else "ffmpeg")
        if bundled_ffmpeg.exists():
            ffmpeg_cmd = str(bundled_ffmpeg)
            logging.info(f"Using bundled ffmpeg: {ffmpeg_cmd}")
        else:
            ffmpeg_cmd = "ffmpeg"
            logging.info("Using system ffmpeg (no bundled ffmpeg found)")

        cmd = [ffmpeg_cmd, "-y", "-i", str(in_path), "-fps_mode", "passthrough", "-q:v", "2", out_pattern]
        try:
            if debug:
                click.echo("  extracting frames with ffmpeg...")
                subprocess.run(cmd, check=False)
            else:
                subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False)
            frames = sorted(repo_tmp_dir.glob(f"frame_{label}_*.jpg"))
            for p in frames:
                try:
                    fimg = Image.open(p).convert("RGB")
                    images.append(fimg)
                except Exception:
                    continue
            extracted_frames_count = len(frames)
            click.echo(f"  extracted {extracted_frames_count} frames via ffmpeg")
        except FileNotFoundError:
            click.echo("ffmpeg not found; unable to extract frames via ffmpeg")

    if not images:
        click.echo("No frames were extracted or detected; aborting calibration.")
        return

    # If frames were extracted via ffmpeg record that at the top of the summary
    try:
        if extracted_frames_count is not None:
            summary_file = repo_tmp_dir / f"summary_{label}.txt"
            # write extraction line first so it appears at top
            logging.info(f"  extracted {extracted_frames_count} frames via ffmpeg")
            with open(summary_file, "a", encoding="utf-8") as sf:
                sf.write(f"  extracted {extracted_frames_count} frames via ffmpeg\n")
    except Exception:
        pass

    # Run selection for each supplied similarity threshold and save results
    for thr in similarity_list:
        selected = _Legacy_select_frames_from_images(images, similarity_threshold=float(thr), max_frames=max_frames)
        click.echo(f"Threshold {thr}: selected {len(selected)} frames")
        # also append the summary line to a summary text file in the calibration folder
        logging.info(f"Threshold {thr}: selected {len(selected)} frames")
        try:
            summary_file = repo_tmp_dir / f"summary_{label}.txt"
            with open(summary_file, "a", encoding="utf-8") as sf:
                sf.write(f"Threshold {thr}: selected {len(selected)} frames\n")
        except Exception:
            pass
        #stop if only one frame is selected
        if len(selected) == 1:
            break


    click.echo(f"Calibration artifacts written to: {repo_tmp_dir}")
    click.echo("IMPORTANT: No tags were written to Hydrus by this command.")

# =============================================================================================================================================




if __name__ == '__main__':
    Image.init()
    ImageFile.LOAD_TRUNCATED_IMAGES = True
    cli.add_command(evaluate_api_batch) # pyright: ignore[reportFunctionMemberAccess]

    cli.add_command(evaluate_api_batch_video) # pyright: ignore[reportFunctionMemberAccess]
    cli.add_command(video_similarity_calibration) # pyright: ignore[reportFunctionMemberAccess]

    cli.add_command(legacy_video_similarity_calibration) # pyright: ignore[reportFunctionMemberAccess]
    cli.add_command(legacy_evaluate_api_batch_video) # pyright: ignore[reportFunctionMemberAccess]
    cli()

