"""Command-line entrypoint for the WD Hydrus Tagger utility.

This module provides a Click-based CLI that queries a Hydrus server for files
and applies tags generated by a local tagging model. It includes helpers to
request files with retry semantics and to run batch evaluations either from a
hash list or by searching Hydrus tags. It also exposes a video-processing
batch command which samples frames from GIFs/videos, aggregates per-frame
tags and writes the combined tags back to Hydrus.

The public commands exported to the Click CLI are:

- ``evaluate_api_batch``: process single-frame images (existing behavior)
- ``evaluate_api_batch_video``: process multi-frame content (GIF/video)

All functions in this module use type hints and Sphinx-style docstrings.
"""

from __future__ import annotations

import os
import os.path
import click # pyright: ignore[reportMissingImports]
from PIL import Image, ImageFile, UnidentifiedImageError
from PIL.Image import Image as PILImage
from . import interrogate
import hydrus_api
from io import BytesIO
import json
import time
import logging
from datetime import datetime
from typing import Any, Optional, cast

import tempfile
import subprocess
import shutil
from pathlib import Path
from PIL import ImageChops, ImageStat

if os.getenv("WD_ALLOW_LARGE_IMAGES", "0") == "1":
    Image.MAX_IMAGE_PIXELS = None

from hydrus_api import APIError


# -----------------------------
# Retry wrapper
# -----------------------------
def get_file_with_retry(client: hydrus_api.Client, file_hash: str, retries: int = 5, delay: int = 5) -> Any:
    """Fetch a file from a Hydrus server with retry semantics.

    The function wraps ``client.get_file`` and will retry transient API
    failures up to ``retries`` times, sleeping ``delay`` seconds between
    attempts. If Hydrus reports a missing file (``FileMissingException``) the
    exception is propagated immediately.

    :param client: Hydrus API client used to fetch files.
    :param file_hash: Hydrus file hash to request.
    :param retries: Number of attempts before giving up.
    :param delay: Seconds to sleep between retry attempts.
    :returns: The response object returned by ``client.get_file``.
    :raises APIError: When Hydrus reports an unrecoverable API error.
    """
    for attempt in range(retries):
        try:
            return client.get_file(file_hash)
        except APIError as e:
            try:
                info = e.response.json()
            except Exception:
                info = {"status_code": getattr(getattr(e, 'response', None), 'status_code', None), "exception_type": None, "text": getattr(getattr(e, 'response', None), 'text', str(e))}

            if info.get("exception_type") == "FileMissingException":
                raise

            if attempt < retries - 1:
                logging.warning(f"retry {attempt} file: {file_hash}")
                time.sleep(delay)
                continue

            logging.error(f"retry fail file: {file_hash}")
            raise


kaomojis: list[str] = [
    "0_0",
    "(o)_(o)",
    "+_+",
    "+_-",
    "._.",
    "<o>_<o>",
    "<|>_<|>",
    "=_=",
    ">_<",
    "3_3",
    "6_9",
    ">_o",
    "@_@",
    "^_^",
    "o_o",
    "u_u",
    "x_x",
    "|_|",
    "||_||",
]


@click.group()
def cli():
    """Top-level Click command group for the WD Hydrus Tagger CLI.

    Commands are registered on this group using :py:meth:`click.Group.add_command`.
    The function body is intentionally empty; Click populates the command
    group at runtime.
    """
    pass


@click.command()
@click.option("--hashfile", help="Text file containing Hydrus hashes")
@click.option("--search-tag", multiple=True,
              help="Hydrus tag(s) to search for (can be used multiple times)")
@click.option("--token", required=True, help="Hydrus API token")
@click.option("--cpu", default=True, help="False to Use GPU instead of CPU")
@click.option("--model", default="wd-eva02-large-tagger-v3",
              help="Tagging model to use")
@click.option("--threshold", default=0.35,
              help="Threshold to drop tags below")
@click.option("--host", default="http://127.0.0.1:45869",
              help="The URL for your Hydrus server ")
@click.option("--tag-service", default="ai tags",
              help="The Hydrus tag service to add tags to")
@click.option("--ratings-only", default=False,
              help="Strip all tags except content rating")
@click.option("--privacy", default=True,
              help="Hide tag output from cli")
@click.option("--debug", is_flag=True, default=False,
              help="Show debug progress and pause before exit")
def evaluate_api_batch(hashfile: Optional[str], search_tag: tuple[str, ...], token: str, cpu: bool,
                       model: str, threshold: float, host: str,
                       tag_service: str, ratings_only: bool, privacy: bool, debug: bool) -> None:
    """Evaluate a batch of single-frame images from Hydrus and add tags.

    This is the existing primary batch command: it either reads file hashes from
    ``hashfile`` or searches Hydrus using ``search_tag`` and applies the
    interrogator to each file, writing tags to the specified Hydrus tag
    service.

    :param hashfile: Optional path to a newline-separated file containing
        Hydrus file hashes to process.
    :param search_tag: One or more Hydrus tags to search for; mutually
        exclusive with ``hashfile``.
    :param token: Hydrus API token for authentication.
    :param cpu: When True, run the interrogator in CPU mode; False to prefer GPU.
    :param model: Local model folder name to load (under ``./model``).
    :param threshold: Minimum tag score threshold to include a tag.
    :param host: URL of the target Hydrus server.
    :param tag_service: Name of the Hydrus tag service to which tags are added.
    :param ratings_only: If True, only the content rating tag is added.
    :param privacy: If True, suppress tag output to the CLI.
    """

    # -----------------------------
    # Setup Logging
    # -----------------------------
    os.makedirs("logs", exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    logfile = f"logs/{model}_{timestamp}.log"

    logging.basicConfig(
        filename=logfile,
        level=logging.INFO,
        format="%(asctime)s - %(message)s"
    )

    logging.info("=== WD HYDRUS TAGGER START ===")
    logging.info(f"Model: {model}")
    logging.info(f"CPU Mode: {cpu}")
    logging.info(f"Tag Service: {tag_service}")

    # -----------------------------
    # Load model info
    # -----------------------------
    if not os.path.isfile('./model/' + model + '/info.json'):
        raise ValueError("info.json not found in model folder!")

    with open('./model/' + model + '/info.json') as json_f:
        modelinfo: dict[str, Any] = json.load(json_f)
        done_hashes_file: str = f"done-hashes-{modelinfo['modelname']}.txt"

    if ratings_only and not modelinfo['ratingsflag']:
        raise ValueError("--ratings-only set, but model does not support ratings!")

    interrogator: interrogate.WaifuDiffusionInterrogator = interrogate.WaifuDiffusionInterrogator(
        modelinfo['modelname'], # the name of the model for display purposes
        modelinfo['modelfile'], # the filename of the model file
        modelinfo['tagsfile'], # the filename of the tags file
        model, # the folder storing the previous two files as well as the info file
		modelinfo['ratingsflag'], # flag indicating whether model identifies content rating
		modelinfo['numberofratings'], # amount of tags to consider for content rating if so
        repo_id=modelinfo['source'], # source of the model, credit where credit is due
    )
    interrogator.load(cpu)

    client: hydrus_api.Client = hydrus_api.Client(token, host)

    # -----------------------------
    # Determine file source
    # -----------------------------
    using_tag_search: bool = False

    if search_tag:
        using_tag_search = True
        #click.echo(f"Searching Hydrus for tags: {search_tag}")
        logging.info(f"Search Tags: {search_tag}")


        # Build a tag list: search tags + system predicate exclusions
        query_tags: list[str] = list(search_tag) + ["system:filetype is not ugoira, video"]
        client.search_files(tags=query_tags)  # warm up the search to avoid first-query lag
        
        hashes: list[str] = cast(list[str], client.search_files(tags=query_tags, return_hashes=True, file_sort_asc=True, file_sort_type=2))


        click.echo(f"Found {len(hashes)} files (excluding ugoira and video).")
        logging.info(f"Found {len(hashes)} files via tag search")

    elif hashfile:
        if not os.path.isfile(hashfile):
            raise ValueError("hashfile not found!")

        with open(hashfile) as f:
            hashes: list[str] = [line.strip() for line in f if line.strip()]

        logging.info(f"Loaded {len(hashes)} hashes from file")

    else:
        raise ValueError("Provide either --search-tag or --hashfile")

    # -----------------------------
    # Done hash tracking (ONLY for hashfile mode)
    # -----------------------------
    done_hashes: set[str] = set()
    bad_hashes: set[str] = set()

    if not using_tag_search:
        if os.path.exists(done_hashes_file):
            with open(done_hashes_file, "r", encoding="utf-8") as f:
                done_hashes = {line.strip() for line in f if line.strip()}

    if os.path.exists("bad-hashes.txt"):
        with open("bad-hashes.txt", "r", encoding="utf-8") as f:
            bad_hashes = {line.strip() for line in f if line.strip()}

    # -----------------------------
    # Processing Loop
    # -----------------------------
    processed_count = 0
    interrupted = False

    try:
        with click.progressbar(hashes) as bar:
            for file_hash in bar:

                file_hash = str(file_hash)

                if not file_hash or file_hash in bad_hashes:
                    continue

                if not using_tag_search and file_hash in done_hashes:
                    continue

                click.echo(" processing: " + file_hash)
                logging.info(f"Processing: {file_hash}")

                try:
                    response: Any = get_file_with_retry(client, file_hash)

                except hydrus_api.APIError as e:
                    try:
                        info = e.response.json()
                    except Exception:
                        info = {"status_code": getattr(getattr(e, 'response', None), 'status_code', None), "exception_type": None, "text": getattr(getattr(e, 'response', None), 'text', str(e))}
                    status = info.get("status_code")
                    etype = info.get("exception_type")
                    click.echo(f"Hydrus error {status} ({etype}) on {file_hash}")
                    logging.warning(f"Hydrus error {status} ({etype}) on {file_hash}")

                    if etype == "FileMissingException":
                        click.echo(f"Added to bad-hashes.txt: {file_hash}")
                        bad_hashes.add(file_hash)
                        with open("bad-hashes.txt", "a", encoding="utf-8") as bad_f:
                            bad_f.write(file_hash + "\n")
                        continue
                    else:
                        # real error, not a bad hash
                        raise
                except RuntimeError as e:
                    click.echo(str(e))
                    click.echo("Hydrus seems unreachable — stopping batch.")
                    logging.error(str(e))
                    logging.error("Hydrus seems unreachable — stopping batch.")
                    raise
                image_bytes: BytesIO = BytesIO(response.content)

                try:
                    image: PILImage = Image.open(image_bytes)
                    image = image.convert("RGB")
                except (UnidentifiedImageError, OSError):
                    click.echo(f"Skipping unreadable or non-image file: {file_hash}")
                    logging.warning(f"Skipping unreadable or non-image file: {file_hash}")
                    bad_hashes.add(file_hash)
                    with open("bad-hashes.txt", "a", encoding="utf-8") as bad_f:
                        bad_f.write(file_hash + "\n")
                    continue

                ratings: dict[str, float]
                tags: dict[str, float]
                ratings, tags = interrogator.interrogate(image)  # pyright: ignore[reportArgumentType]

                rating: str = "none"
                if modelinfo['ratingsflag']:
                    ratings["none"] = 0.0
                    for key in ratings.keys():
                        if ratings[key] > ratings[rating]:
                            rating = key

                clipped_tags: list[str] = []

                if not ratings_only:
                    for key in tags.keys():
                        if tags[key] > threshold:
                            clipped_tags.append(
                                key.replace("_", " ") if key not in kaomojis else key
                            )
                if not privacy:
                    click.echo("rating: " + rating)
                    click.echo("tags: " + ", ".join(clipped_tags))
                    click.echo()

                if modelinfo['ratingsflag']:
                    clipped_tags.append("rating:" + rating)

                if ratings_only:
                    clipped_tags.append(
                        "ratings only " + modelinfo['modelname'] + " ai generated tags"
                    )
                else:
                    clipped_tags.append(
                        modelinfo['modelname'] + " ai generated tags"
                    )

                client.add_tags(
                    hashes=[file_hash],
                    service_names_to_tags={tag_service: clipped_tags} # pyright: ignore[reportCallIssue]
                )

                processed_count += 1

                # Only write done-hash if using hashfile mode
                if not using_tag_search:
                    done_hashes.add(file_hash)
                    with open(done_hashes_file, "a", encoding="utf-8") as done_f:
                        done_f.write(file_hash + "\n")

                # --- Micro pause: let tag write commit ---
                time.sleep(0.1)
                # --- Macro pause: only every 200 files ---
                if processed_count % 200 == 0:
                    time.sleep(3)
                    logging.info(f"Processed {processed_count} files")

    except KeyboardInterrupt:
        interrupted = True
        click.echo("\n⚠ Interrupted by user (Ctrl+C)")
        logging.warning("=== INTERRUPTED BY USER (CTRL+C) ===")

    finally:
        logging.info("=== WD HYDRUS TAGGER FINISHED ===")
        logging.info(f"Total processed: {processed_count}")

        if interrupted:
            logging.info("Run ended due to manual interruption.")
        else:
            logging.info("Run completed normally.")

        logging.shutdown()

        click.echo(f"\nFinished. Total processed: {processed_count}")

        if debug:
            try:
                click.echo("Debug mode: press Enter to exit.")
                input()
            except Exception:
                # If stdin is not available, ignore and continue exiting
                pass
        
    

def _select_frames_from_images(images: list[PILImage], similarity_threshold: float = 6.0, max_frames: int = 40) -> list[PILImage]:
    """Select a subset of frames from a sequence by simple similarity filtering.

    The function performs a lightweight pairwise comparison using resized
    grayscale frame differences and only keeps a frame if it is sufficiently
    different from the last-kept frame. This reduces redundant frames and
    controls processing cost.

    :param images: Sequence of PIL images (RGB) to filter.
    :param similarity_threshold: Mean-difference threshold to decide if two
        frames are different enough to keep.
    :param max_frames: Maximum number of frames to keep.
    :returns: A list of selected PIL images.
    """
    selected: list[PILImage] = []
    last_small = None
    for img in images:
        small = img.copy().resize((64, 64)).convert("L")
        if last_small is None:
            selected.append(img)
            last_small = small
        else:
            diff = ImageChops.difference(small, last_small)
            stat = ImageStat.Stat(diff)
            mean_diff = sum(stat.mean) / len(stat.mean)
            if mean_diff >= similarity_threshold:
                selected.append(img)
                last_small = small
        if len(selected) >= max_frames:
            break
    return selected


@click.command()
@click.option("--hashfile", help="Text file containing Hydrus hashes")
@click.option("--search-tag", multiple=True,
              help="Hydrus tag(s) to search for (can be used multiple times)")
@click.option("--token", required=True, help="Hydrus API token")
@click.option("--cpu", default=True, help="False to Use GPU instead of CPU")
@click.option("--model", default="wd-eva02-large-tagger-v3",
              help="Tagging model to use")
@click.option("--threshold", default=0.35,
              help="Threshold to drop tags below")
@click.option("--host", default="http://127.0.0.1:45869",
              help="The URL for your Hydrus server ")
@click.option("--tag-service", default="ai tags",
              help="The Hydrus tag service to add tags to")
@click.option("--ratings-only", default=False,
              help="Strip all tags except content rating")
@click.option("--privacy", default=True,
              help="Hide tag output from cli")
@click.option("--debug", is_flag=True, default=False,
              help="Show debug progress for video processing")
def evaluate_api_batch_video(hashfile: Optional[str], search_tag: tuple[str, ...], token: str, cpu: bool,
                             model: str, threshold: float, host: str,
                             tag_service: str, ratings_only: bool, privacy: bool, debug: bool) -> None:
    """Evaluate a batch of multi-frame content (GIF/video) and apply tags.

    This command is similar to :func:`evaluate_api_batch` but targets
    multi-frame content. For animated GIFs the frames are read via PIL; for
    other video containers the function will attempt to use ``ffmpeg`` (if
    available) to extract one frame per second. Frames are dynamically
    filtered for similarity before interrogation for efficiency.

    The per-frame tag scores are aggregated (averaged) and the resulting tag
    list is applied to the original video file in Hydrus.

    :param hashfile: Optional path to a newline-separated file containing
        Hydrus file hashes to process.
    :param search_tag: One or more Hydrus tags to search for; mutually
        exclusive with ``hashfile``.
    :param token: Hydrus API token for authentication.
    :param cpu: When True, run the interrogator in CPU mode; False to prefer GPU.
    :param model: Local model folder name to load (under ``./model``).
    :param threshold: Minimum tag score threshold to include a tag.
    :param host: URL of the target Hydrus server.
    :param tag_service: Name of the Hydrus tag service to which tags are added.
    :param ratings_only: If True, only the content rating tag is added.
    :param privacy: If True, suppress tag output to the CLI.
    """

    # Setup logging and model like the image batch command
    os.makedirs("logs", exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    logfile = f"logs/{model}_{timestamp}.log"

    logging.basicConfig(
        filename=logfile,
        level=logging.INFO,
        format="%(asctime)s - %(message)s"
    )

    logging.info("=== WD HYDRUS VIDEO TAGGER START ===")
    logging.info(f"Model: {model}")
    logging.info(f"CPU Mode: {cpu}")
    logging.info(f"Tag Service: {tag_service}")
    # Clean up repository-local ffmpeg temporary files from previous runs
    try:
        repo_root = Path(__file__).resolve().parents[1]
        repo_tmp_dir = repo_root / "ffmpeg_temp"
        if repo_tmp_dir.exists():
            for p in repo_tmp_dir.iterdir():
                try:
                    if p.is_dir():
                        shutil.rmtree(p)
                    else:
                        p.unlink()
                except Exception:
                    # ignore individual cleanup errors
                    pass
    except Exception:
        logging.exception("Failed to clean ffmpeg_temp at startup")

    if not os.path.isfile('./model/' + model + '/info.json'):
        raise ValueError("info.json not found in model folder!")

    with open('./model/' + model + '/info.json') as json_f:
        modelinfo: dict[str, Any] = json.load(json_f)
        done_hashes_file: str = f"done-hashes-{modelinfo['modelname']}.txt"

    if ratings_only and not modelinfo['ratingsflag']:
        raise ValueError("--ratings-only set, but model does not support ratings!")

    interrogator: interrogate.WaifuDiffusionInterrogator = interrogate.WaifuDiffusionInterrogator(
        modelinfo['modelname'],
        modelinfo['modelfile'],
        modelinfo['tagsfile'],
        model,
        modelinfo['ratingsflag'],
        modelinfo['numberofratings'],
        repo_id=modelinfo['source'],
    )
    interrogator.load(cpu)

    client: hydrus_api.Client = hydrus_api.Client(token, host)

    # Determine file source (search for video-like content)
    using_tag_search: bool = False

    if search_tag:
        using_tag_search = True
        logging.info(f"Search Tags: {search_tag}")
        # Include only animated/video types
        query_tags: list[str] = list(search_tag) + ["system:filetype is ugoira, video"]
        client.search_files(tags=query_tags)
        hashes: list[str] = cast(list[str], client.search_files(tags=query_tags, return_hashes=True, file_sort_asc=True, file_sort_type=1))
        click.echo(f"Found {len(hashes)} files (animated/video).")
        logging.info(f"Found {len(hashes)} files via tag search")

    elif hashfile:
        if not os.path.isfile(hashfile):
            raise ValueError("hashfile not found!")

        with open(hashfile) as f:
            hashes: list[str] = [line.strip() for line in f if line.strip()]

        logging.info(f"Loaded {len(hashes)} hashes from file")

    else:
        raise ValueError("Provide either --search-tag or --hashfile")

    done_hashes: set[str] = set()
    bad_hashes: set[str] = set()

    if not using_tag_search:
        if os.path.exists(done_hashes_file):
            with open(done_hashes_file, "r", encoding="utf-8") as f:
                done_hashes = {line.strip() for line in f if line.strip()}

    if os.path.exists("bad-hashes.txt"):
        with open("bad-hashes.txt", "r", encoding="utf-8") as f:
            bad_hashes = {line.strip() for line in f if line.strip()}

    processed_count = 0
    interrupted = False

    try:
        with click.progressbar(hashes) as bar:
            for file_hash in bar:
                file_hash = str(file_hash)

                if not file_hash or file_hash in bad_hashes:
                    continue

                if not using_tag_search and file_hash in done_hashes:
                    continue

                click.echo(" processing: " + file_hash)
                logging.info(f"Processing: {file_hash}")

                try:
                    response: Any = get_file_with_retry(client, file_hash)

                except hydrus_api.APIError as e:
                    info = e.response.json()
                    status = info.get("status_code")
                    etype = info.get("exception_type")
                    click.echo(f"Hydrus error {status} ({etype}) on {file_hash}")
                    logging.warning(f"Hydrus error {status} ({etype}) on {file_hash}")

                    if etype == "FileMissingException":
                        click.echo(f"Added to bad-hashes.txt: {file_hash}")
                        bad_hashes.add(file_hash)
                        with open("bad-hashes.txt", "a", encoding="utf-8") as bad_f:
                            bad_f.write(file_hash + "\n")
                        continue
                    else:
                        raise
                except RuntimeError as e:
                    click.echo(str(e))
                    click.echo("Hydrus seems unreachable — stopping batch.")
                    logging.error(str(e))
                    logging.error("Hydrus seems unreachable — stopping batch.")
                    raise

                images: list[PILImage] = []

                # Try to open as an animated image first (GIF, APNG via PIL)
                try:
                    image_bytes = BytesIO(response.content)
                    img = Image.open(image_bytes)
                    if getattr(img, "is_animated", False) or getattr(img, "n_frames", 1) > 1:
                        for i in range(getattr(img, "n_frames", 1)):
                            img.seek(i)
                            frame = img.convert("RGB").copy()
                            images.append(frame)
                        click.echo(f"  found {len(images)} frames via PIL animation")
                    else:
                        img.close()
                except Exception:
                    images = []

                # If not an animated image, attempt ffmpeg frame extraction
                tmpdir = None
                if not images:
                    # prefer using a repo-local temporary directory instead of
                    # the system/AppData temp folder so extracted frames stay
                    # inside the repository
                    repo_root = Path(__file__).resolve().parents[1]
                    repo_tmp_dir = repo_root / "ffmpeg_temp"
                    repo_tmp_dir.mkdir(parents=True, exist_ok=True)
                    in_path = repo_tmp_dir / f"input_{file_hash}"
                    with open(in_path, "wb") as f:
                        f.write(response.content)

                    out_pattern = str(repo_tmp_dir / f"frame_{file_hash}_%05d.jpg")
                    # Prefer bundled ffmpeg in the repository under ./ffmpeg/bin,
                    # otherwise fall back to system `ffmpeg` on PATH.
                    repo_root = Path(__file__).resolve().parents[1]
                    bundled_ffmpeg = repo_root / "ffmpeg" / "bin" / ("ffmpeg.exe" if os.name == "nt" else "ffmpeg")
                    if bundled_ffmpeg.exists():
                        ffmpeg_cmd = str(bundled_ffmpeg)
                        logging.info(f"Using bundled ffmpeg: {ffmpeg_cmd}")
                    else:
                        ffmpeg_cmd = "ffmpeg"
                        logging.info("Using system ffmpeg (no bundled ffmpeg found)")

                    # extract all frames; ffmpeg may be absent — ignore errors
                    # use -vsync 0 to avoid duplicate/drop frames, output as images
                    cmd = [ffmpeg_cmd, "-y", "-i", str(in_path), "-fps_mode", "passthrough", "-q:v", "2", out_pattern]
                    try:
                        if debug:
                            click.echo("  extracting frames with ffmpeg...")
                            subprocess.run(cmd, check=False)
                        else:
                            click.echo("  extracting frames with ffmpeg...")
                            subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False)
                        frames = sorted(repo_tmp_dir.glob(f"frame_{file_hash}_*.jpg"))
                        for p in frames:
                            try:
                                fimg = Image.open(p).convert("RGB")
                                images.append(fimg)
                            except Exception:
                                continue
                        click.echo(f"  extracted {len(frames)} frames via ffmpeg")
                    except FileNotFoundError:
                        # ffmpeg not found; treat as unreadable video
                        images = []

                if not images:
                    click.echo(f"Skipping unreadable or unsupported multi-frame file: {file_hash}")
                    logging.warning(f"Skipping unreadable or unsupported multi-frame file: {file_hash}")
                    bad_hashes.add(file_hash)
                    with open("bad-hashes.txt", "a", encoding="utf-8") as bad_f:
                        bad_f.write(file_hash + "\n")
                    # remove any ffmpeg files produced for this hash
                    try:
                        for p in repo_tmp_dir.glob(f"frame_{file_hash}_*.jpg"): # pyright: ignore[reportPossiblyUnboundVariable]
                            try:
                                p.unlink()
                            except Exception:
                                pass
                        in_file = repo_tmp_dir / f"input_{file_hash}" # pyright: ignore[reportPossiblyUnboundVariable, reportOperatorIssue]
                        if in_file.exists():
                            try:
                                in_file.unlink()
                            except Exception:
                                pass
                    except Exception:
                        pass
                    continue

                selected = _select_frames_from_images(images)
                click.echo(f"  selected {len(selected)} frames after similarity filtering")

                # Aggregate tags over selected frames
                agg_scores: dict[str, float] = {}
                agg_ratings: dict[str, float] = {}
                frames_processed = 0
                total_frames = len(selected)
                click.echo(f"  starting tagging of {total_frames} frames")

                def _show_idx(item) -> str:
                    # item is a (idx, frame) tuple when using enumerate
                    try:
                        idx = item[0]
                        return f"{idx+1}/{total_frames}"
                    except Exception:
                        return ""

                enumerated = list(enumerate(selected))
                with click.progressbar(enumerated, label="Tagging frames", length=total_frames, item_show_func=_show_idx) as pbar:
                    for idx, frame in pbar:
                        ratings, tags = interrogator.interrogate(frame)
                        for t, s in tags.items():
                            agg_scores[t] = agg_scores.get(t, 0.0) + float(s)
                        for r, s in ratings.items():
                            agg_ratings[r] = agg_ratings.get(r, 0.0) + float(s)
                        frames_processed += 1

                if frames_processed == 0:
                    click.echo(f"No usable frames for {file_hash}")
                    logging.warning(f"No usable frames for {file_hash}")
                    # remove any ffmpeg files produced for this hash
                    try:
                        for p in repo_tmp_dir.glob(f"frame_{file_hash}_*.jpg"): # pyright: ignore[reportPossiblyUnboundVariable]
                            try:
                                p.unlink()
                            except Exception:
                                pass
                        in_file = repo_tmp_dir / f"input_{file_hash}" # pyright: ignore[reportPossiblyUnboundVariable, reportOperatorIssue]
                        if in_file.exists():
                            try:
                                in_file.unlink()
                            except Exception:
                                pass
                    except Exception:
                        pass
                    continue

                # Ensure all selected frames were actually processed before sending tags
                if frames_processed != total_frames:
                    click.echo(f"Incomplete frame processing ({frames_processed}/{total_frames}) for {file_hash} — skipping tag write")
                    logging.warning(f"Incomplete frame processing ({frames_processed}/{total_frames}) for {file_hash} — skipping tag write")
                    # cleanup ffmpeg files for this hash
                    try:
                        for p in repo_tmp_dir.glob(f"frame_{file_hash}_*.jpg"): # pyright: ignore[reportPossiblyUnboundVariable]
                            try:
                                p.unlink()
                            except Exception:
                                pass
                        in_file = repo_tmp_dir / f"input_{file_hash}" # pyright: ignore[reportPossiblyUnboundVariable, reportOperatorIssue]
                        if in_file.exists():
                            try:
                                in_file.unlink()
                            except Exception:
                                pass
                    except Exception:
                        pass
                    continue

                click.echo(f"  processed {frames_processed} frames for {file_hash}")

                # average scores across frames
                for k in list(agg_scores.keys()):
                    agg_scores[k] /= frames_processed
                for k in list(agg_ratings.keys()):
                    agg_ratings[k] /= frames_processed

                # Pick rating as the highest-averaged rating key
                rating = "none"
                if modelinfo['ratingsflag']:
                    agg_ratings.setdefault("none", 0.0)
                    for key in agg_ratings.keys():
                        if agg_ratings[key] > agg_ratings[rating]:
                            rating = key

                clipped_tags: list[str] = []
                if not ratings_only:
                    for key, score in agg_scores.items():
                        if score > threshold:
                            clipped_tags.append(key.replace("_", " ") if key not in kaomojis else key)

                if not privacy:
                    click.echo("rating: " + rating)
                    click.echo("tags: " + ", ".join(clipped_tags))
                    click.echo()

                if modelinfo['ratingsflag']:
                    clipped_tags.append("rating:" + rating)

                if ratings_only:
                    clipped_tags.append("ratings only " + modelinfo['modelname'] + " ai generated tags")
                else:
                    clipped_tags.append(modelinfo['modelname'] + " ai generated tags")

                client.add_tags(
                    hashes=[file_hash],
                    service_names_to_tags={tag_service: clipped_tags} # pyright: ignore[reportCallIssue]
                )

                processed_count += 1

                if not using_tag_search:
                    done_hashes.add(file_hash)
                    with open(done_hashes_file, "a", encoding="utf-8") as done_f:
                        done_f.write(file_hash + "\n")

                time.sleep(0.1)

                # cleanup ffmpeg files created for this hash
                try:
                    for p in repo_tmp_dir.glob(f"frame_{file_hash}_*.jpg"): # pyright: ignore[reportPossiblyUnboundVariable]
                        try:
                            p.unlink()
                        except Exception:
                            pass
                    in_file = repo_tmp_dir / f"input_{file_hash}" # pyright: ignore[reportPossiblyUnboundVariable, reportOperatorIssue]
                    if in_file.exists():
                        try:
                            in_file.unlink()
                        except Exception:
                            pass
                except Exception:
                    pass

                if processed_count % 200 == 0:
                    time.sleep(3)
                    logging.info(f"Processed {processed_count} files")

    except KeyboardInterrupt:
        interrupted = True
        click.echo("\n⚠ Interrupted by user (Ctrl+C)")
        logging.warning("=== INTERRUPTED BY USER (CTRL+C) ===")

    finally:
        logging.info("=== WD HYDRUS VIDEO TAGGER FINISHED ===")
        logging.info(f"Total processed: {processed_count}")

        if interrupted:
            logging.info("Run ended due to manual interruption.")
        else:
            logging.info("Run completed normally.")

        logging.shutdown()

        click.echo(f"\nFinished. Total processed: {processed_count}")

        if debug:
            try:
                click.echo("Debug mode: press Enter to exit.")
                input()
            except Exception:
                # If stdin is not available, ignore and continue exiting
                pass


if __name__ == '__main__':
    Image.init()
    ImageFile.LOAD_TRUNCATED_IMAGES = True
    cli.add_command(evaluate_api_batch) # pyright: ignore[reportFunctionMemberAccess]
    cli.add_command(evaluate_api_batch_video) # pyright: ignore[reportFunctionMemberAccess]
    cli()
